### ISSUE TITLE
suggestion: rel additions

### ISSUE THREAD

**Issue by geemus** [json-schema/json-schema#103]
In addition to `instances` and `create` it seems like it might be useful to have the other CRUD rels available. ie `delete` and `update` both have different connotations than `self` and similar to `create`. `delete` could then also specify that it SHOULD use a non-safe method. What do you think?

**Comment by handrews** [comment]
@geemus 
All of these proposed relations have been removed from the latest standard by @awwright
You can catch up with what's going on at https://github.com/json-schema-org/json-schema-spec
including various issues discussing things related to this.
Could you please close this issue?  We no longer have permissions on this repo.
