### ISSUE TITLE
Section for guides/introductions

### ISSUE THREAD

**Issue by geraintluff** [json-schema/json-schema#106]
The [Space Telescope Science Institute](http://www.stsci.edu/portal/) wrote a (very nice-looking) guide to JSON Schema, aimed at schema authors: http://spacetelescope.github.io/understanding-json-schema/

We should link to it from the main site.

**Comment by handrews** [comment]
Pull requests welcome at https://github.com/json-schema-org/json-schema-org.github.io
This repo is deprecated, and it would be much appreciated if you could close this issue as no one remaining has permissions to do so.
