### ISSUE TITLE
Making it easier to do ACL (Access Control Lists) and session security?

### ISSUE THREAD

**Issue by gavinengel** [json-schema/json-schema#115]
Let's say I create a json-schema for a database containing Drupal records.  I then use a API framework, such as PHP F3, on top of a Drupal json-schema to pull records directly from the database via Ajax.

I would need some sort of session/login validation.  Some records are only meant to be read if the user is currently logged in.  

Is there anything in the specification dealing with ACL for databases?  For instance, let's say a table can only be read from by users with role 'admin'.  So I suppose what I would be looking for is a way to assign create/remove/update/delete permissions on the table & row level.  And I'd want to be able to do it by checking not only the roles of the logged in user, but the id of the logged in user (let's say a table can be read from, but only the row assigned to the logged in user).

In the end, I'd want the following pieces for api.example.com:
1. a database
2. a json-scheme which can handle ACL and also data validation
3. a API framework which can connect # 1 and # 2 with the web user

I am not seeing the "ACL" portion in the specs for json-schema.  Is there an add-on schema perhaps which expands json-schema into ACL validation so that the process can be standardized?

**Comment by coderofsalvation** [comment]
I was thinking in a similar way.
One could add something like a permission-field like so:

    "some_field": {
       ....
        "permissions":[
            "role_foo": { crud:{ c:true, r:true, u:true, d:false} }
            "role_bar": { crud:{ c:true, r:true, u:true, d:false} }
        ]
    }

@gavinengel Let me know if you stumble upon any ACL-specification on top of jsonschema. I would be interested for sure.

ps. I find myself throwing around parts of one big jsonschema into any areas, not only dataconsumer:

    db                 <--                 --> api response
    api spec           <-- jsonschema      --> html form
    backend functions  <--                 --> frontend js

Usually I just tailor the jsonschema to its audience (leaving stuff out when serving to dataconsumers)

**Comment by gavinengel** [comment]
One method of ACL for a web API would probably also work for databases: http://docs.strongloop.com/display/public/LB/Controlling+data+access;jsessionid=C8C38A11B73FF2E8181F5A6621C1B59F

I doubt a json-schema ACL "standard" is even possible, although I think there could definitely be some commonly used implementations.  Maybe some for SQL, NoSQL, both, etc.  One for Mongo: npmjs.com/package/acl

**Comment by coderofsalvation** [comment]
indeed, in the meantime, while I was at it, I created this:

https://www.npmjs.com/package/jsonschema-acl

just some acl sauce on top of jsonschema.
