### ISSUE TITLE
Proposal: `patch`, `merge`; how to definitely get rid of the `additionalProperties` problem

### ISSUE THREAD

**Issue by fge** [json-schema/json-schema#120]
Already posted to the mailing list; but really, I think this is THE solution to at last get rid of that infamous problem.

Rationale:
- it is counterintuitive to most people that by default, if unspecified, additional object members are allowed by default in a JSON object instance;
- people who do understand the role of `additionalProperties` rightly complain that this makes it very hard to complement the definition of a JSON Object-based format with JSON Schema;
- the proposed solution to require validators to implement two modes (undeclared properties forbidden or allowed) is unacceptable: it is impossible to convey the required behaviour within the schema itself;
- my proposal is based on well-defined specifications;
- while it requires some schema preprocessing, so does the proposed `$data`;
- my proposal is unambiguous.

So, here is the proposal again, modified from the one on the mailing list. First some examples:

``` json
{
    "merge": {
        "source": { "$ref": "source://schema/here#" },
        "with": { "json": [ "patch-merge", "here" ] }
    }
}
```

``` json
{
    "patch": {
        "source": { "$ref": "source://schema/here#" },
        "with" [ "well-formed", "RFC 6902", "JSON Patch", "here" ]
    }
}
```

Rules:
- `$ref` STILL takes precedence over those two;
- implementations MUST support at least "merge";
- implementations MAY support "patch"; if they do, they MUST consider as invalid a schema containing both "patch" and "merge";
- other schema keywords, if any, SHALL be ignored;
- implementations MUST use the result of merging/patching as the schema to be processed.

Also, a different `$schema` should be used according to whether implementations support `patch` or not.

**Comment by willfarrell** [comment]
Looking forward to seeing `$merge` in the v5 spec. I noticed (merge)[https://github.com/fge/json-schema-validator/wiki/v5:-merge] isn't included in the (proposal)[https://github.com/json-schema/json-schema/wiki/v5-Proposals], curious as to what's holding up `$merge` from being included. It would allow my schema files to be significantly cleaner and more maintainable.

**Comment by handrews** [comment]
This discussion has been moved to https://github.com/json-schema-org/json-schema-spec/issues/15

**Comment by handrews** [comment]
@fge would you be willing to close this since there is a new issue tracking it?  There's no one left who can close issues for us here.
