### ISSUE TITLE
Refactor thinking on the IETF

### ISSUE THREAD

**Issue by laconbass** [json-schema/json-schema#130]
I've been reading the [last] · [drafts] · [on] the IETF site, and I felt sad whe I saw how outdated they are.

[last]: http://datatracker.ietf.org/doc/draft-zyp-json-schema/
[drafts]: http://datatracker.ietf.org/doc/draft-fge-json-schema-validation/
[on]: http://tools.ietf.org/html/draft-luff-json-hyper-schema-00

[Is JSON Schema dead?](https://www.ietf.org/mail-archive/web/apps-discuss/current/msg07015.html), asked myself. Fortunately [I ended up reading things](https://www.ietf.org/mail-archive/web/apps-discuss/current/msg07015.html) that lead me here, to our beloved github :smile:, and I see that it's **not dead**.

Reading the words of *F. Galiege*, It seems that was frustrating the path of writting, reviewing, and refactoring that drafts, specially for the bad - either unexistent - feedback.  Am I wrong? If so, correct me please.

While comparing the text of the last core draft with [other json-related drafts](http://datatracker.ietf.org/doc/search/?name=json&rfcs=on&activeDrafts=on&oldDrafts=on&search_submit=), I've found many things that, IMHO:

- could be refactored to meet the *technical style* of the IETF; and
- could be refactored to demonstrate the utility of such an spec;

It's clear enough for me, as I work everyday with node.js, that having a JSON based tool for data validation that I can reuse both on  backend and frontend is for sure a good thing. I'm lucky cause [such a tool](http://json-schema.org) already exist, so I wonder if it could be effectively adopted as standard because **if [it has been living - and growing - on the wild](https://www.npmjs.org/search?q=json-schema), is because the community likes it**.

I like the work you are putting here, so I would like to help refactoring that IETF draft and see if together we can get over [the red line of the internet standards experts](http://tools.ietf.org/html/rfc2360), and build a standard spec together.

I don't know if this team has plan on continuing the path to that standard spec, so that's obviously the first question I need feedback from you :laughing: 

Keep up the good work,
L.

**Comment by bjaanes** [comment]
Year later. Has much happened?

**Comment by akuckartz** [comment]
Meanwhile JSON-LD has become a standard...

**Comment by hugovincent** [comment]
@geraintluff how is draft-5 coming along?

**Comment by handrews** [comment]
@laconbass @bjaanes @akuckartz @hugovincent 
New IETF drafts have been submitted by @awwright
New spec work is going on here: https://github.com/json-schema-org/json-schema-spec
Could you please close this issue?  We no longer have permissions to this repo.

https://tools.ietf.org/html/draft-wright-json-schema-00
https://tools.ietf.org/html/draft-wright-json-schema-validation-00
https://tools.ietf.org/html/draft-wright-json-schema-hyperschema-00

(minor revision to Draft 04, with a more substantial update in active discussion at the new repo)

**Comment by laconbass** [comment]
Closing this issue as requested by @handrews, future readers: please follow to https://github.com/json-schema-org/
