### ISSUE TITLE
Link to SchemaStore.org

### ISSUE THREAD

**Issue by madskristensen** [json-schema/json-schema#131]
In an attempt to provide better tooling around JSON Schemas, I've started http://schemastore.org as a collection of JSON Schemas for known JSON files such as `.jshintrc`, `packages.json`, `bower.json` etc.

The idea is to have an API with a list of JSON schemas that tooling can automatically map to various known JSON files. Both validators, editors and other tooling can then use the API to get a list of available schemas as well as get auto-mapping of known .json file names to their matching schema.

If you currently have schemas then you can either host them for free at schemastore.org or simply just add a URL pointer to them in the API. This ensures that the schemas can be decentralized and that schemastore.org just acts as a discoverability and mapping API for tooling.

The goal is to:

1. Provide a broad list of JSON Schemas
2. Support tooling through auto-mapping of .json files to their schema
3. 100% Open source
4. Provide hosting for schemas that aren't currently hosted anywhere
5. Write plugins for SublimeText et al. that provides auto-completion based on a .json files schema
6. CDN support for all hosted schemas and the API (coming soon...)

I'm interested in knowing what you think about this idea of a centralized schema store for decentralized schemas? Hopefully this will help drive tooling adoption for JSON Schemas.

**Comment by handrews** [comment]
@madskristensen The web site repo has moved to https://github.com/json-schema-org/json-schema-org.github.io if you feel inspired to pick this work up again :-)
Could you please close this issue?  We no longer have the necessary permissions on this repo to do so.
