### ISSUE TITLE
json-schema.org/address example wrong usage of required keyword

### ISSUE THREAD

**Issue by PaulFreund** [json-schema/json-schema#132]
{
    "description": "An Address following the convention of http://microformats.org/wiki/hcard",
    "type": "object",
    "properties": {
        "post-office-box": { "type": "string" },
        "extended-address": { "type": "string" },
        "street-address": { "type": "string" },
        "locality":{ "type": "string", "required": true },
        "region": { "type": "string", "required": true },
        "postal-code": { "type": "string" },
        "country-name": { "type": "string", "required": true}
    },
    "dependencies": {
        "post-office-box": "street-address",
        "extended-address": "street-address"
    }
}

The required keyword has to be an array with at least one element, see the Validation specification 5.4.3.1.

**Comment by handrews** [comment]
@PaulFreund @madskristensen 
This repo is deprecated now.  If you would like to take a look and see if a new pull request is needed, the web site and examples live at https://github.com/json-schema-org/json-schema-org.github.io
Could you please close this issue?

**Comment by PaulFreund** [comment]
Closed because of deprecation ;)
