### ISSUE TITLE
Rename "format" and define it as a whitespace-separated list of values

### ISSUE THREAD

**Issue by brettz9** [json-schema/json-schema#135]
I'd like to suggest renaming "format" to something which does not inherently suggest anything to do with display formatting but rather purely suggests providing additional, optional, custom semantic validation, something like "x-types" or "custom-types".

While custom validation types may no doubt have formatting implications, I don't believe the spec should encourage inline styling hints (in disregard of separation-of-concerns) by using the "format" terminology. Another reason for the suggested name change is because some validators may of course operate with custom validation but without any styling whatsoever, or editors may choose to validate but not display in a distinct manner.

And I indicated the plural for these custom types (e.g., "x-types") because, if it is for custom validation, multiple types should be possible (and even genuine formatting tools could find a way to handle some cases of multiple formatting). Being forced to define hybrid format names like "urlOrPlainString" would not be a pleasant solution. The spec might not currently prohibit whitespace separated tokens, but I think it would help to endorse this approach if implementations will use the attribute, and know that they can ignore tokens that they do not support while supporting those that they do.

**Comment by handrews** [comment]
@brettz9 Work has moved to https://github.com/json-schema-org/json-schema-spec
Could you please close this?  It looks as if it did not get traction, but if you think it is worth discussing again do feel free to re-file it at the new repo.
