### ISSUE TITLE
Proposal JSON as an xml refer parser

### ISSUE THREAD

**Issue by L2L2L** [json-schema/json-schema#143]
ESON(JSON) take the roll of a parser that represent the browser document of any base xml file for elements.

var doc = new ESON.DOM();
doc.load(myPage.xhtml);

This could reference each node name on a lower case representation; for example, the p element will have the represent name of p. This is all kept in the variable container doc, so no name space conflict.

**Comment by handrews** [comment]
@L2L2L 
If I understand E4X correctly, this is outside of the scope of the JSON Schema project.  In any event, work on JSON Schema is now at https://github.com/json-schema-org/json-schema-spec so please close this issue.  If you really think this is in-scope for JSON Schema, please re-open it at the new repository.
