### ISSUE TITLE
Please add Manatee.Json to list of implementations

### ISSUE THREAD

**Issue by gregsdennis** [json-schema/json-schema#156]
Please see https://bitbucket.org/gregsdennis/manatee.json for the source and wiki.  It's also available on Nuget.

Manatee.Json will validate and generate schema.

Thank you.

**Comment by handrews** [comment]
JSON Schema web site work has moved to https://github.com/json-schema-org/json-schema-org.github.io
Could you please close this issue?  You can just submit a pull request at the new repo if you'd like.

**Comment by gregsdennis** [comment]
Will do.  Thanks for the info.
