### ISSUE TITLE
flat $ref

### ISSUE THREAD

**Issue by jon49** [json-schema/json-schema#157]
[I was working through the example underneath `Tying this all together`.](http://spacetelescope.github.io/understanding-json-schema/structuring.html) I was wondering if I could do something like below:

```js
var schema = {
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

        "properties": {
          "$ref": "#/definitions/address",
          "type": { "enum": [ "residential", "business" ] },
          "required": ["type"]
        }
}

var json2 = {
    street_address: 1,
    "city": "Washington",
    "type": "business"
}

var validate = validator(schema)
console.log(json2)
console.log('should be valid', validate(json2))
console.log(validate.errors)
```

My expectation is that it should be an error since `street_address` is `1` and not a `string`. I expect that it will also error since `state` isn't supplied.

I should note that this behavior isn't the same when I make the ref similar to:

```js
  "type": "object",

        "properties": {
          address: {"$ref": "#/definitions/address"},
          "type": { "enum": [ "residential", "business" ] },
          "required": ["type"]
        }
```

The above will error out when the `address` schema isn't applied to.

**Comment by fge** [comment]
No, this is not an error.

Each object member defined in `properties` is expected to be found in the target instance; and in your first example, you expect to find properties by name `$ref`, `type` and `required`, and only `type` exists in the target instance.

In your second example, what you do have is a schema for a member named `address`, but again, in the target schema, there is no such member.

**Comment by bugventure** [comment]
+1

Also, in a schema, an object with a `$ref` member is always a JSON reference. According to the [JSON Pointer spec](http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03): 

> Any members other than "$ref" in a JSON Reference object SHALL be
   ignored.

This means that, in your first case, the `type` and `required` schema members should be ignored, because the object contains a `$ref` member, making it a JSON reference.

**Comment by trajano** [comment]
@bugventure the spec can be interpreted as 
> Any members other than "$ref" in a JSON Reference object SHALL be
ignored. *Only for the context for JSON Reference Objects*

In which case it may be good to add in the JSON Schema spec a capability of extending what is referenced with things that are provided on the local schema.  The validation should include the following checks though:

### For any type

* "type" may not be overriden, if specified the schema is not valid

### For objects

* Additional properties may be added, but changing an existing property is not allowed in the referring schema.  (This makes implementation a bit easier I think)
* `required` will add additional required fields but not take any out.  So on validation, the required field will combine both the ones specified locally and the ones in the `$ref`
* `dependencies` will add additional dependencies but not take any out.  So on validation, the required field will combine both the ones specified locally and the ones in the `$ref`

### For strings

* Another pattern can be specified, but both the referred pattern and the defined pattern need to be valid.  This applies to all the patterns in the tree.
* `enum` cannot be replaced if defined in the `$ref`, but it can be defined locally

### For numbers

* `minimum`, `maximum`, `exclusiveMinimum`, `exclusiveMaximum` can be specified, but both the one `$ref` pattern and the defined limits need to be valid.

**Comment by sam-at-github** [comment]
:-1: Why is this open?
