### ISSUE TITLE
Pick a name for the new json-schema github org

### ISSUE THREAD

**Issue by Relequestual** [json-schema/json-schema#173]
As discussed in https://github.com/json-schema/json-schema/issues/167, the state of the json-schema org on github is locked with a user who is not responding to communication. It was suggested that a new github org would be created to regain full control.

Please give your suggestions! =]

**Comment by Relequestual** [comment]
Suggestions: json-schema-org, json-schemas (because there's json schema and json hyper-schema)

**Comment by fge** [comment]
And why not just jsonschema?

**Comment by Relequestual** [comment]
Personally, readability.

**Comment by fge** [comment]
json-schema-interest?

**Comment by donaldpipowitch** [comment]
+1 json-schema-org

**Comment by geraintluff** [comment]
I went for [json-schema-org](https://github.com/json-schema-org) initially due to its similarity to our domain name.  However, I'll rename it to whatever the consensus is.

**Comment by Relequestual** [comment]
Curious, how come the repo is ~200 ahead?

**Comment by bugventure** [comment]
+1 json-schema-org

**Comment by geraintluff** [comment]
@Relequestual - it's not, it's level with the `gh-pages` branch.  I assume GitHub's comparing the two `master` branches, which isn't meaningful.

**Comment by Relequestual** [comment]
ahhhh right. so that's now the repo for the site? I thought we wanted to start from scratch for that? (or shall we do so on a dev branch and leave master there so the repo is in fact still powering the site?)

**Comment by Relequestual** [comment]
There are some limitations on forked repos. Might it be better to simply change remotes on a local repo? should preserve the history still.

**Comment by geraintluff** [comment]
The new repo isn't (yet) powering json-schema.org, but it is available on http://json-schema-org.github.io/.

I wasn't aware of forked repos being fundamentally different - I thought it was just some metadata that GitHub stored.  If it's causing problems, we can reset it - we can also ask for the "forked from" status to be removed by GitHub support.

**Comment by Relequestual** [comment]
The only limited feature is you can't search within them code wise (weird I know, but that's how it is). I wasn't aware that you can get the "forked from" status removed. Sounds like a way forward.

**Comment by sam-at-github** [comment]
> we can also ask for the "forked from" status to be removed by GitHub support.
Why would you want that? I think it's a mistake. Keep the history.

**Comment by Relequestual** [comment]
IF it causes problems, we CAN. Although @geraintluff 's preverbial radio has been silent for some time now =[
