### ISSUE TITLE
How to contribute to site?

### ISSUE THREAD

**Issue by Zearin** [json-schema/json-schema#175]
I know the website lives on the `gh-pages` branch.  But each document is written in several formats, and…
- I can’t find anything that says which format(s) are considered “source”
- I don’t know how to test whether my changes are okay with the build process
- I have no idea what the build process is

A GitHub convention is to have a `CONTRIBUTING.md` file at the top level with answers to questions like these, and any other useful info for people who want to contribute.  I recommend it.

In the meantime, if I want to contribute to the site docs, which format(s) do I edit?

**Comment by Relequestual** [comment]
Currently, there are number of issues surrounding the project. This involves the website.
Please see https://github.com/json-schema/json-schema/issues/167

(tl;dr: I'm looking at re-doing the website!)

**Comment by handrews** [comment]
@Zearin You can now find the site and specification at:
https://github.com/json-schema-org/json-schema-org.github.io
https://github.com/json-schema-org/json-schema-spec

Could you please close this issue?  There is no one left with the project who is able to close issues in this deprecated repo.
