### ISSUE TITLE
Identity property

### ISSUE THREAD

**Issue by heruan** [json-schema/json-schema#178]
How can one specify a property which identifies JSON data? E.g. a web application retrieves an object: `GET http://example.org/items/123`
````json
{
	"id": 123,
	"code": "ABC",
	"description": "Foo"
}
````
and then a set of items: `GET http://example.org/baskets/1`
````json
{
	"id": 1,
	"items": [
		{
			"id": 111,
			"code": "XYZ",
			"description": "Bar"
		},
		{
			"id": 123,
			"code": "ABC",
			"description": "Foo"
		}
	]
}
````
The web application also retrieves the JSON schemas: `GET http://example.org/items/$schema`
````json
{
	"title": "Item",
	"type": "object",
	"properties": {
		"id": {
			"type": "number"
		},
		"code": {
			"type": "string"
		},
		"description": {
			"type": "string"
		}
	},
	"required": ["id", "code"]
}
````
and `GET http://example.org/baskets/$schema`
````json
{
	"title": "Basket",
	"type": "object",
	"properties": {
		"id": {
			"type": "number"
		},
		"items": {
			"type": "array",
			"items": {
				"$ref": "http://example.org/items/$schema"
			}
		}
	},
	"required": ["id"]
}
````
How can I specify in the JSON schema of the items that the `id` property identifies the object (and not for example the `code` property, which may change)?

**Comment by sam-at-github** [comment]
In general you can't. JSON Schema does not have a unique key constraint. Expressing constraints across greater than one instance, like for example `id` is unique among this collection of instances is outside the scope of JSON Schema draft v4. The context of validation is a single instance not a collection of instances. You could however arbitrarily extend JSON schema with your own special words:

    {
      ...
      "properties": {
        "id": {
            "type": "number"
            "title": "unique id of instance",
            "isUniqueKey": true
        },
      }
    }

Find a parser that will allow you to easily hook into the `isUniqueKey` is another question. I think this is better left to business logic outside JSON Schema.

**Comment by heruan** [comment]
I understand, thank you! For draft v5 I'd propose a `key` property which would be an array with the name of the properties defining the identity of the instance.

**Comment by jdesrosiers** [comment]
Hi @heruan,

The best way to designate an identifier for an object is to use JSON Hyper-Schema to define a `self` or `full` `link`.

```json
{
    "title": "Item",
    "type": "object",
    "properties": {
        "id": {
            "type": "number"
        },
        "code": {
            "type": "string"
        },
        "description": {
            "type": "string"
        }
    },
    "required": ["id", "code"],
    "links": [
        {
            "rel": "self",
            "method": "GET",
            "href": "/items/{id}"
        }
    ]
}
```

**Comment by heruan** [comment]
Great idea, @jdesrosiers! The `self`-link `href` can be safely used as key to identify the object within the map. Thank you!
