### ISSUE TITLE
Multiple media types in JSON Hyper Schema

### ISSUE THREAD

**Issue by DimDragon** [json-schema/json-schema#179]
Lets have an endpoint returning JSON payload in different JSON formats
```
GET /api/books/
Accept: application/json
```
returns base JSON format, where
```
GET /api/books/
Accept: application/vnd.somevendor+json
```
returns same data formatted differently according some public standard. Looking at current JSON Hyper Schema it seems, we have something like:
```
{
	"type": "object",
	"properties": { ..book properties },
	"links": [
		{
			"href": "/api/books/",
			"rel": "instances"
		},
		{
			"href": "/api/books/",
			"rel": "alternate",
			"mediaType": "application/vnd.somevendor+json",
			"targetSchema": {
				"$ref": "some vendor schema"
			}
		}
	]
}
```
Usage of ```alternate``` relation seems weird here since we still return book instances only under different formatting.

Another problematic part is the correlation of schema and instance over HTTP. If I return:
```
Content-Type: application/json; profile=http://example.com/schema/books#
```
It makes sense in this case, but when request and response is for the second type, things look grim since receiving party must actually scan ```links``` in order to find proper schema

Whole media type example http://json-schema.org/latest/json-schema-hypermedia.html#anchor33 seems off suggesting format alternation via url instead of HTTP headers. For example quote from Mark Masses REST API Cookbook on that subject reads:

"**Rule: Media type negotiation should be supported when multiple representations are available**

Allow clients to negotiate for a given format and schema by submitting an Accept header with the desired media type."

Finally note how in this book ```schema``` keyword is suggested for correlation, while JSON Schema suggests ```profile```

**Comment by jdesrosiers** [comment]
> Usage of `alternate` relation seems weird here since we still return book instances only under different formatting.

Agreed.  Typically, you wouldn't define more than one link in this case.  However, you could create multiple links like in your example if you want to hint to the user-agent what each of the acceptable media-types are.  I don't think `alternate` is appropriate in this case.  I would make both links `instances`.

> when request and response is for the second type, things look grim since receiving party must actually scan `links` in order to find proper schema

This doesn't make sense to me.  I assume you mean that the receiving party must look up the `targetSchema`?  This should not be the case.  `targetSchema` is advisory only.  It doesn't know what the schema of the actual response will be.  It's a hint.  The authority on how the response should be interpreted is the response itself.  This is a core principle in REST and HTTP.  The way it seems you are using the vendor media-type, the schema would be implicit in the media-type.  If not, you can always use the `profile` `Content-Type` attribute or the `describedBy` `Link` header with your vendor media-type.

> Whole media type example http://json-schema.org/latest/json-schema-hypermedia.html#anchor33 seems off

Yeah, it's not really best practice, but it's not technically an incorrect use HTTP and it serves to illustrate the use of the keyword.

> Finally note how in this book `schema` keyword is suggested for correlation, while JSON Schema suggests `profile`

Everyone has an opinion.  The book you mention is far from authoritative on the subject.  I can't speak to the decision process that led to `profile` being chosen, but I would stick with it considering that it is what the JSON Schema specification defines and it is the most widely adpoted.  Personally, I prefer the `describedBy` `Link` header correlation method, but I tend to use `profile` instead because that's what most people expect to see.

**Comment by DimDragon** [comment]
Probably I was not clear enough on correlation problem. You actually nailed the problem:

> The authority on how the response should be interpreted is the response itself. This is a core principle in REST and HTTP.

It is all about content negotiation via media type. Lets assume I make the call:
```
GET /api/books/
Accept: application/json
```
Response is
```
Content-Type: application/json; profile=http://example.com/schema/books#
{
	"author": "Dimitar Draganov",
	"title": "REST API",
	"price": 2.45,
	"price_currency": "USD",
	"isbn": "1974821682"
}
```
This is the default JSON payload of that service, but it must also support popular format of some vendor of this same data so if I do:
```
GET /api/books/
Accept: application/vnd.somevendor+json
```
Response is:
```
Content-Type: application/vnd.somevendor+json; profile=http://example.com/schema/books#
{
	"title": "REST API",
	"author": {
		"first_name": "Dimitar",
		"last_name": "Draganov"
	},
	"meta": {
		"price": { "value": 2.45, "currency": "USD" },
		"number": "1974821682"
	}
}
```
Both responses correlate to single schema http://example.com/schema/books#, which makes second case hard to interpret. For a real project I ended up creating separate schemes for different media types and served them again based on media type, which at least gives consuming side a chance to include returned content-type along with schema request and get correct one.

Usage of two schemes however makes them unaware of each other, so working with one media type you will not be aware that endpoint serves the other, so you may need to include the other types in BOTH schemes...a bit of a catch22 problem I'm having. 

What you would consider a proper way to express use case I'm describing?

I completely agree on rest of your notes and indeed ```profile``` is good enough and no semantics can beat adoption!

**Comment by jdesrosiers** [comment]
I think you defiantly need two separate schemas to describe each response.  I would also suggest a third schema that contains the common elements so you can avoid duplication between the two.

For example

`http://example.com/schema/book`
```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "allOf": [{ "$ref": "http://example.com/schema/book-common" }],
  "title": "Book",
  "type": "object",
  "properties": {
    "author": { "type": "string" },
    "title": { "type": "string" },
    "price": { "type": "number", "minimum": 0 },
    "price_currency": { "enum": ["USD", "CAD"] },
    "isbn": { "type": "string" }
  }
}
```

`http://example.com/schema/book-alternate`
```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "allOf": [{ "$ref": "http://example.com/schema/book-common" }],
  "title": "Book Alternate View",
  "type": "object",
  "properties": {
    "title": { "type": "string" },
    "author": {
      "type": "object",
      "properties": {
        "first_name": { "type": "string" },
        "last_name": { "type": "string" }
      }
    },
    "meta": {
      "type": "object",
      "properties": {
        "price": {
          "type": "object",
          "properties": {
            "value": { "type": "number", "minimum": 0 },
            "currency": { "enum": ["USD", "CAD"] }
          }
        },
        "number": { "type": "string" }
      }
    }
  }
}
```

`http://example.com/schema/book-common`
```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "title": "Book Common Elements",
  "links": [
    {
      "rel": "instances",
      "href": "/api/books"
    },
    {
      "rel": "instances",
      "href": "/api/books",
      "mediaType": "application/vnd.somevendor+json"
    }
  ]
}
```

Including the third schema introduces a little more complexity, but I think it is worth it to eliminate the duplication.  I wouldn't worry too much about any duplication between the alternate representations.  It's the `links` duplication that I would want to avoid.

**Comment by DimDragon** [comment]
So we are in agreement, this use case simply needs separate schemes. There is nothing wrong with this approach but I still feel uneasy about it for two reasons:

- availability of ```mediaType``` keyword in hyper schema, kind of suggests you can describe such cases where your endpoint returns different types or does content negotiation. In practice however if you also want to correlate to that schema, you simply need to split
- second problem I'm having is that I don't use hyper schema only for correlation but also to generate documentation for our REST API endpoints. So instead of using solely hyper schema semantics I now had to build additional logic based on multiple schema presence.

Links 'inclusion' in your sample is clever, however your common schema is basically just meta data, while ```allOf``` is still just a validation keyword (I definitely get what your aim is here since in my projects I also use ```allOf``` constantly as basic object inheritance :-). I also render ```instances``` as array of schema described so this creates a bit of an issue and since the split is already there and you deal with only one of the schemes at given time, I can live with the duplication. I also add ```targetSchema``` to hint that ```instances``` returns other format. My preference based on your sample would be something like:

http://example.com/schema/book
```
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "title": "Book",
  "type": "object",
  "properties": { ... }
  "links": [
    {
      "rel": "instances",
      "href": "/api/books"
    },
    {
      "rel": "instances",
      "href": "/api/books",
      "mediaType": "application/vnd.somevendor+json",
      "targetSchema": {
        "$ref": "http://example.com/schema/book-alternate#"
      }
    }
  ]
}
```

http://example.com/schema/book-alternate
```
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "title": "Book Alternate",
  "type": "object",
  "properties": { ... }
  "links": [
    {
      "rel": "instances",
      "href": "/api/books",
      "targetSchema": {
        "$ref": "http://example.com/schema/book#"
      }
    },
    {
      "rel": "instances",
      "href": "/api/books"
      "mediaType": "application/vnd.somevendor+json"
    }
  ]
}
```

Thank you for taking the time to discuss this problem. I really think hyper schema is quite suitable to serve as JSON REST API description language, just needs few tweaks and additions to be able to cover more scenarios. If this falls under scope of this project I will be happy to provide some ideas and use case samples

**Comment by jdesrosiers** [comment]
> availability of `mediaType` keyword in hyper schema, kind of suggests you can describe such cases where your endpoint returns different types or does content negotiation

I don't think `mediaType` was ever designed or intended to describe content negotiation.  If it was, it would allow an array of media-types.  Without the ability to specify multiple media-types, it is necessary to duplicate links.  `targetSchema` has the same limitations.

> Links 'inclusion' in your sample is clever, however your common schema is basically just meta data, while allOf is still just a validation keyword

Yes, I agree this interpretation is questionable.  However, there is a need for something like this.

I think something like the following would be needed to describe content negotiation.

```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "title": "Book",
  "type": "object",
  "properties": { ... }
  "links": [
    {
      "rel": "instances",
      "href": "/api/books",
      "contentNegotiation": [
        {
          "mediaType": "application/json",
          "targetSchema": { "$ref": "http://example.com/schema/book#" }
        },
        {
          "mediaType": "application/vnd.somevendor+json",
          "targetSchema": { "$ref": "http://example.com/schema/book-alternate#" }
        }
      ]
    }
  ]
}
```

**Comment by DimDragon** [comment]
Now I agree with you on 100%, such construction is exactly what I would like to see available in JSON Hyper schema, where in your sample I would assume both ```mediaType``` and ```targetSchema``` are not just advisory! 

Please note it also covers nicely situation, where you are not the author of all target schemes. My last sample actually only works because both schemes are written by me and I can add those ```links```. With your proposal you can use such top level schema only to control negotiation and correlation and keep actual instance schemes aside. Well done!

Should this go into: https://github.com/json-schema/json-schema/wiki/v5-Proposals ? There are some very good proposals in there, I have already picked up and implemented some of them in order to turn Hyper schema into REST API description language.

**Comment by jdesrosiers** [comment]
> I would assume both `mediaType` and `targetSchema` are not just advisory!

No, I think they would still be advisory only.  These values describe what the response will be.  I believe Hyper Schema should only require what the request should be.  The user-agent should never be dependent on receiving a particular response.

> With your proposal you can use such top level schema only to control negotiation and correlation and keep actual instance schemes aside.

In fact, I would like to take this even farther.  I would like to see Hyper Schema decoupled from JSON Schema.  I see no reason why Hyper Schema shouldn't be able to describe an XML API or even use a JSON schema standard that isn't JSON Schema.

> Should this go into: https://github.com/json-schema/json-schema/wiki/v5-Proposals ?

Absolutely, but it needs a lot more thought before it is ready for a formal proposal.  This was just off the top of my head.  I'd like to consider all the ways content negotiation could be used and make sure nothing is left out.

**Comment by DimDragon** [comment]
>  The user-agent should never be dependent on receiving a particular response.

This is true in general, but I believe in this case of content negotiation we are describing possible 'contracts' user-agent can take with the endpoint. Way I think about it is: I open car dealership and announce (via Hyper schema) I sell Porsche and Ferrari, so if you request to buy a Ferrari, I should not supply you with a....Ford. By including certain media type I make a 'promise' to support it and should honor it. I may be totally wrong on this one, but this is how I grasp the concept in general.

>  I see no reason why Hyper Schema shouldn't be able to describe an XML API or even use a JSON schema standard that isn't JSON Schema.

This is quite bold statement! I'm bit torn on it. From one side I see what you mean and possibility to describe all format or mixed APIs and this plays nice as far as media type goes. Taking this route however would mean that ```targetSchema``` should actually just be a 'link' to actual schema and Hyper schema will not provide you with enough information how to read it. So meta schema will lose some of it expression potential. Probably some in the middle approach, where ```targetSchema``` is kept for JSON Schema and something new is added to support link references to other format schemes, can cover both cases. Still I have hard time weighting pros and cons on that one...

As for the formal proposal, I hope to hear other people opinions on that topic, apart from our nice dialogue :-)

**Comment by DimDragon** [comment]
@jdesrosiers : I have spent some time thinking over your proposal and comments. Since ```mediaType``` + ```targetSchema``` describe response, same considerations apply for ```encType``` + ```schema```, which describe request. In order to keep it inline with v4 and leaving the whole advisory discussion aside for now, I have come up with:
```
"mediaType": {
	"anyOf": [
		{
			"description": "media type (as defined by RFC 2046) describing the link target",
			"type": "string"
		},
		{
			"description": "provide target schema for multiple media types",
			"type": "object",
			"additionalProperties": { "$ref": "#" }
		}
	]
}
```
To keep ```targetSchema``` even when using multiple media types you can state something in lines of: "In case ```mediatType``` is missing or ```mediaType``` is an ```object``` with no matching property, then ```targetSchema``` represents expected outcome."

Another approach could be to turn types into array:
```
"mediaType": {
	"anyOf": [
		{
			"description": "media type (as defined by RFC 2046) describing the link target",
			"type": "string"
		},
		{
			"description": "provide target schema for multiple media types",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"value": { "type": "string" },
					"targetSchema": { "$ref": "#" }
				}
			}
		}
	]
}
```
Like stated, same can be done for ```encType```. While not necessary good practice some APIs provide content negotiation by use of custom headers, to cover such cases, dedicated array for content negotiation as shown in your sample is probably better. Finally to support non JSON objects descriptors you can turn values per type into something like:
```
"describedBy": {
	"oneOf": [
		{ "$ref": "#" },
		{
			"type": "string",
			"format": "uri"
		}
	]
}
```
This last one is bit conflicting with LDO relation ```describedBy```, which in theory can cover such cases, but again doesn't play well with multiple types at same URI.

**Comment by jdesrosiers** [comment]
> I believe in this case of content negotiation we are describing possible 'contracts' user-agent can take with the endpoint.

Content negotiation as defined in the HTTP spec implies no such contract.  For one thing, a server is not required to return a response in one of the client specified acceptable media-types.  One of the core principles of REST is to decouple the client and server.  A contract between client and server would seem to be contrary to that goal.

> Taking this route however would mean that `targetSchema` should actually just be a 'link' to actual schema and Hyper schema will not provide you with enough information how to read it.

I don't think it is a problem for Hyper Schema to not know about the validation standard being used.  It just needs to define how the two standards interact.  Composing software components is a good practice, so why not composing standards.

> The default fragment resolution protocol is "json-pointer", which is defined below. Other fragment resolution protocols MAY be used
> - http://json-schema.org/latest/json-schema-hypermedia.html#anchor8

You can see from this quote from the spec that Hyper Schema already allows for something like this.  It allows a standard other than JSON Pointer to be used for fragment resolution.  What I am talking about is no different.  It's just delegating the validation functionality to another standard.  No expressiveness is lost.  Some of that expressiveness is just delegated to another standard.

**Comment by sebilasse** [comment]
@DimDragon Did you maybe mean [media](http://json-schema.org/latest/json-schema-hypermedia.html#anchor10) and not mediaType ?

**Comment by DimDragon** [comment]
@sebilasse Nope. ```media``` keyword is meant to represent non-JSON data and ONLY along with ```string``` type. What I have as real life example is service endpoint returning JSON payload in multiple formats and using content negotiation to choose one.

**Comment by handrews** [comment]
@DimDragon 
JSON Schema spec work has moved to https://github.com/json-schema-org/json-schema-spec.
Could you please close this issue?  You are welcome to re-open it at the new repository for further consideration/discussion.
