### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by brettz9** [json-schema/json-schema#180]
Hi,

Would you be open to a PR for Bower support?

**Comment by jdesrosiers** [comment]
@brettz9, you have the wrong github repo.  This repo is for the json-schema *specification*.  It contains no implementation in any language.  There are several JavaScript implementations out there, but there is nothing here Bower would be interested in.

**Comment by brettz9** [comment]
Actually, I am aware this is only the specification, but because it is defined in JSONSchema, I intend to generate a UI to allow users to edit JSON schemas and the spec itself would be used to define what was allowable in the editing interface.

**Comment by jdesrosiers** [comment]
Ahhh, I didn't consider the meta schemas.  You have a good point.  I agree that having those in Bower could be useful.

btw, I like your editor idea.  I've been playing with a toy program with a similar spec-driven approach.  My idea is a validator that is entirely plugin based where the meta schema is used to define which plugins to load.  This should not only make it easier for people to add custom extensions, but also force them to properly define their extensions by writing their own meta schemas.

**Comment by oleics** [comment]
+1, but with npm.

and yes, the idea is to create json-schemas based on the json-schema for json-schemas (always wanted to write this ^^)

**Comment by handrews** [comment]
@brettz9 , @oleics 
JSON Schema spec work has moved to https://github.com/json-schema-org/json-schema-spec.
Could you please close this issue?  You are welcome to re-open it at the new repository for further consideration/discussion.

**Comment by brettz9** [comment]
@handrews : Thanks, raised at https://github.com/json-schema-org/json-schema-spec/issues/105
