### ISSUE TITLE
Add "messages" property.

### ISSUE THREAD

**Issue by johnmanko** [json-schema/json-schema#183]
Add a "messages" property to define custom messages for validation keys.  

Example:

``` javascript
{
    title: "Name",
    type: "String",
    minLength: 4,
    maxLength: 6,
    messages: {
        minLength: "Your name must be at least four characters long.",
        maxLengh: "Your name must be no more than six characters long"
    }
}
```

Related:
https://github.com/geraintluff/tv4/issues/115
https://github.com/geraintluff/tv4/pull/206

**Comment by geraintluff** [comment]
<i>\*puts spec hat on\*</i> :stuck_out_tongue:

For the examples you've provided, this feels like it could be assembled by a more intelligent error reporter.

The schema already expresses the constraint that "the `"name"` field (called "Name" in `title`) must be 4 characters long".  Could a decent error reporter not assemble a natural language description from this information?

**Comment by johnmanko** [comment]
True, or custom messages the implementation could allow for template vars.  Also consider:
```
{
    title: "Password",
    type: "pattern",
    pattern: '^[a-zA-Z0-9@#\\$%]{8,20}$',
    messages: {
        pattern: "%title% must be 8-20 characters and must contain only alpha-numeric character or the following @, #, $, %"
    }
}
```
How will that be generated by a library?  If it's purely an implementation detail, then we lose the benefit of storing the message with the schema (where we already have the constraints defined).  Not to mention that the developer will now need to know how to interpret the field/property validation error, because any validation implementation will only offer generic formatted messages.   Allowing custom message in the spec I can just take that message to push it to the user, and the intent is documented with constraints.

For instance, here is how JPA does it:

```java
@Entity 
public class Address implements Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    @Column(length = 36, nullable = false)
    @NotNull(message = "All entities require a UUID")
    protected String uuid = UUID.randomUUID().toString();

    @Column(length = 255, nullable = false)
    @NotNull(message="Street Address is required")
    private String streetAddress;

    @Column(length = 255)
    @NotNull(message="City is required")
    private String city;

    @Column(length = 255)
    private String county;

    @Column(length = 2, nullable = false)
    @Size(min = 2, max = 2, message = "State must be two characters")
    @NotNull(message="State is required")
    private String state;

    @Column(length = 5)
    @Size(min = 5, max = 5, message = "Zip must be 5 digits in length")
    @NotNull(message="Zip is required")
    private String zip5;

    @Column(length = 4)
    @RequiredIfPresent(regex = "^[0-9]{4}$", message = "Zip ext must be 4 digits in length")
    private String zip4;

}
```

Just my $0.02.

**Comment by geraintluff** [comment]
Should this be closed?  Is this covered by custom extensions and error reporting (as in the corresponding tv4 issue), or are you still proposing this as a general-purpose solution?

**Comment by johnmanko** [comment]
I'd like to see this part of the spec, but I closed it because I didn't think it was going anywhere.  If it's something that the team would still considering, then I'd be more than happy to reopen it.  I think it's important.

**Comment by nisha14mani** [comment]
If type is string, then it works good.. For integer or number, i changed my code according to it.. But its not working.

**Comment by handrews** [comment]
@johnmanko work has moved to https://github.com/json-schema-org/json-schema-spec , please close this and, if you still want to have it considered for the next draft, re-file it at the new repo.

**Comment by johnmanko** [comment]
I moved this to https://github.com/json-schema-org/json-schema-spec/issues/148
