### ISSUE TITLE
Unclear is pattern value is a RegExp body or RegExp literal

### ISSUE THREAD

**Issue by mauritsl** [json-schema/json-schema#188]
The value for the pattern property must be a ECMA 262 regular expression;
http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.2.3

The ECMA 262 defines an "regular expression body" and a "regular expression literal". The JSON spec is not clear what it demands.
http://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5

Note that all given JSON schema examples are using a "regular expression body". The specification should mention if literals are allowed, disallowed or optionally.

**Comment by awwright** [comment]
A "regular expression literal" is something invented by ECMA 262 for its syntax. JSON Schema is certainly referring to the ECMA 262 regular expression body production.

That is, the value expected is the same that you would pass to RegExp e.g. `new RegExp(pattern)`
