### ISSUE TITLE
address should not require locality and region

### ISSUE THREAD

**Issue by trajano** [json-schema/json-schema#189]
There's nothing on hcard that indicates that locality and region are both required.  Some countries have no notion of "region/states/provinces"

However, if you have a region it should imply that there's a locality.
I suggest 

```
{
"$schema": "http://json-schema.org/draft-04/schema#",
"description": "An Address following the convention of http://microformats.org/wiki/hcard",
"type": "object",
"properties": {
    "post-office-box": { "type": "string" },
    "extended-address": { "type": "string" },
    "street-address": { "type": "string" },
    "locality":{ "type": "string" },
    "region": { "type": "string" },
    "postal-code": { "type": "string" },
    "country-name": { "type": "string"}
},
"required": ["locality", "country-name"],
"dependencies": {
    "region": ["locality"],
    "post-office-box": ["street-address"],
    "extended-address": ["street-address"]
}
}
```

**Comment by AaronBratcher** [comment]
I would also say that post-office-box should not require a street-address.

Mr Smith
PO BOX 123
Some City, State   ZIP

**Comment by kw217** [comment]
I think specifying any dependencies is unwise. Not all countries have localities: consider "Pope Francis, Apostolic Palace, 00120 Vatican City". which is name, street-address, postal-code, country-name.

**Comment by handrews** [comment]
Work on this project has moved to https://github.com/json-schema-org/json-schema-spec
If you are still interested in this proposal, please re-file it there.
