### ISSUE TITLE
Support for min/maxLength on object property names

### ISSUE THREAD

**Issue by frontierpsycho** [json-schema/json-schema#193]
It might be useful to be able to set limits on property names when defining them with `patternProperties`. 

For example, I have an object which should have arbitrary key-value pairs, and I want to constrain the keys to be at most 64 characters. For now, I've resorted to this:

``` json
"additionalProperties": false,
"patternProperties": {
   "^\\S{1,64}$" : { ... }
}
```

However, the error message generated is very confusing. For example, if I send this object:

``` json
{ "SIXTYFOURCHARACTERSYOUSAYWELLALRIGHTTHENLETSNOTEXCEEDTHATSHALLWEIMEANWHONEEDSMORETHANSIXTYFOURCHARACTERSANYWAY":"value"}
```

I get the following error, which is clear to someone familiar with JSON-schema and the additional properties keyword, but not to everyone else:

`SIXTYFOURCHARACTERSYOUSAYWELLALRIGHTTHENLETSNOTEXCEEDTHATSHALLWEIMEANWHONEEDSMORETHANSIXTYFOURCHARACTERSANYWAY: Additional properties not allowed` 

I suggest support for something like:

``` json
"patternProperties": {
  "^\\S*$": {
    "maxLength": 64,
    ...
  }
}
```

With the corresponding error message:

``````
SIXTYFOURCHARACTERSYOUSAYWELLALRIGHTTHENLETSNOTEXCEEDTHATSHALLWEIMEANWHONEEDSMORETHANSIXTYFOURCHARACTERSANYWAY: Property name is too long (110 chars), maximum 64```
``````

**Comment by handrews** [comment]
Work on this project has moved to https://github.com/json-schema-org/json-schema-spec
If you are still interested in this proposal, please re-file it there.
