### ISSUE TITLE
Grammar and formal semantics

### ISSUE THREAD

**Issue by CSWR** [json-schema/json-schema#195]
Hello everyone

Here at [CSWR Chile](http://www.ciws.cl) we are interested in studying JSON Schema, but we needed a formal mathematical model for the specification.
##### [This is what we came up with](http://cswr.github.io/JsonSchema/).

We tried to make it such that it conforms to everything that's in the standard, but we needed it to be unambiguous, so we had to take a few choices on the way. I think we are going to need this if we want JSON Schema to become an IETF standard.

Also, the syntax is not in the usual grammar that the IETF uses, but it is very easy to change.

We hope this can be of use to you as well, and we would really appreciate if you can give us any feedback. We are open to suggestions on how to improve the definitions and to clarify any mistakes that we made while interpreting the standard. 

Juan

**Comment by karimofthecrop** [comment]
I think it would be interesting to note the specific choices you made along the way.

**Comment by seagreen** [comment]
Interesting. The issues of "well formedness" you address [here](http://cswr.github.io/JsonSchema/spec/grammar/#well-formedness) are something I've struggled with (for instance see this PR: https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/107). It would be great to get some more guidance about this in the next spec.

**Comment by handrews** [comment]
@CSWR I believe this falls under json-schema-org/json-schema-spec#5 at the new repository.

Could you please close this?  This repo is deprecated and there is no one left with the project who can close issues here.
