### ISSUE TITLE
Schemas stored at json-schema.org are outdated

### ISSUE THREAD

**Issue by stefk** [json-schema/json-schema#198]
These two URIs:

- http://json-schema.org/schema#
- http://json-schema.org/draft-04/schema#

return a schema without the `format` keyword definition.

I didn't check the other URIs listed in the spec ([core 6.1](http://json-schema.org/latest/json-schema-core.html#anchor23)). Shouldn't the update be automated ?

**Comment by vearutop** [comment]
Indeed, I just faced same problem with missing `format` in `properties` definition, making all schema invalid. It is a shame to have main public link broken for 7+ months already.

**Comment by handrews** [comment]
@stefk this has been fixed in the new repo at json-schem-org/json-schema-spec and will soon be propagated to the web site.

Could you please close this issue?  No one still remaining with the project has permissions to close things here.

**Comment by stefk** [comment]
I'm closing but I see your fix is already +1 month old and the schemas aren't up-to-date yet (which is the main issue). Not sure I understand the policy.

**Comment by handrews** [comment]
@stefk you are correct, I've opened an issue to track the follow-through on the new site repo.  (I don't know that there is an actual policy, I'm just trying to clean up this old repo- thanks for closing this issue).
