### ISSUE TITLE
Even number of elements in array

### ISSUE THREAD

**Issue by dinizime** [json-schema/json-schema#200]
There is any way to enforce an array to have even length? Make sense to use custom format to solve this case?

``` javascript
{
    "type": "array"
    "minItems": 4,
    "items": {"type": "number"},
    "format": "evenArray"
}
```

**Comment by epoberezkin** [comment]
I think formats are best reserved for strings. Custom keywords seem to be a better way to achieve it.

**Comment by handrews** [comment]
@dinizime could you please close this and, if you'd like to discuss it further, re-open at [json-schema-org/json-schema-spec](https://github.com/json-schema-org/json-schema-spec/issues)?

No one still active with the projects has permissions to close these issues otherwise.
