### ISSUE TITLE
Specific link relation for JSON-Schema

### ISSUE THREAD

**Issue by dinizime** [json-schema/json-schema#201]
Currently the specification uses the relation type "describedBy" from RFC 5988. This is not very informative for autonomous agents using an application. A specific link relation for JSON-Schema, such as "http://json-schema.org/json-schema" would help agents that are JSON-Schema aware to know where to search for the schema.

**Comment by handrews** [comment]
"describedBy" and "profile" are discussed in depth at https://github.com/json-schema-org/json-schema-spec/issues/9 which has been closed due to an update of the specification language.

**Comment by handrews** [comment]
@dinizime if the discussion in json-schema-org/json-schema-spec#9 sufficiently addresses your concerns, could you please close this?  (almost no one currently active with the project has permissions to close issues they don't own in this repo).
