### ISSUE TITLE
Citing JSON-schema

### ISSUE THREAD

**Issue by shachibista** [json-schema/json-schema#203]
Hi!

I have specified the JSON data in my thesis in terms of JSON-schema. What is the recommended/preferred citation strategy?

Thanks!

**Comment by sam-at-github** [comment]
Bit late, but just cite the thing your talking about... If your citing the spec specifically the spec at [IETF spec publication](https://www.ietf.org/archive/id/draft-zyp-json-schema-04.txt) would be the most authoritative.

**Comment by handrews** [comment]
@shachibista Could you please close this?  There's no one left with permissions at this old repository to close other people's issues.  Please join us at json-schema-org/json-schema-spec for further discussion if you'd like!
