### ISSUE TITLE
patternGroups (v5 proposal)

### ISSUE THREAD

**Issue by epoberezkin** [json-schema/json-schema#206]
I think they should not replace patternProperties, then can be simply added.

If I don't care about maximums / minimums it's just more verbose I think.

Or you think there is no such use case when I shouldn't care?

I think that at least one use case is when I have only one group of properties with pattern I can use minProperties / maxProperties to achieve the same.

**Comment by handrews** [comment]
@epoberezkin could you please close this and re-open at the new repository if needed?

**Comment by epoberezkin** [comment]
added as https://github.com/json-schema-org/json-schema-spec/issues/117
