### ISSUE TITLE
Schema selection based on property value

### ISSUE THREAD

**Issue by niquola** [json-schema/json-schema#207]
May I specify schema based on property value? 

The simple example is {type: 'Person',...} and {type: 'Animal', ..}. I want validation would be dispatched to Person or Animal schema based on type property value.

**Comment by Ixrec** [comment]
It sounds like oneOf would do what you want:

{
    oneOf: [
        { type: 'object', properties: {
            type: { enum: ['Person'] },
            somePersonProperty: ...,
        }},
        { type: 'object', properties: {
            type: { enum: ['Animal'] },
            someAnimalProperty: ...,
        }},
    ]
}

**Comment by handrews** [comment]
@niquola :  Further discussion on this general idea is being tracked in issue #64 .  Could you please close this issue in favor of that one?
