### ISSUE TITLE
Property name restriction based on values of array

### ISSUE THREAD

**Issue by ASnow** [json-schema/json-schema#210]
I want get validation schema for something like this:
```
{
  "base_keys_collection": [
    {"name": "key1"}, // "keyN" is just for example it could be any string
    {"name": "key2"},
    {"name": "key3"}
  ],
  "base_values_collection": [
    {"name": "value1"}, // "valueN" is just for example it could be any string
    {"name": "value2"},
    {"name": "value3"}
  ],
  "target_validated_collection": {
    "key1": ["value1", "value2"],
    "key2": ["value1", "value3"]
  }
}
```
it should validate `target_validated_collection` properties by `base_keys_collection/*/name` and `target_validated_collection` property's values by `base_values_collection/*/name`

I think it could be done by definitions. We should define `Keys` and `Values` and use them as templates  for object properties.

**Comment by handrews** [comment]
@ASnow this repository is deprecated, and there's no one left who can do things like close issues here.

Could you close this and, if still interested, open it at [json-schema-org/json-schema-spec](https://github.com/json-schema-org/json-schema-spec/issues) instead?

**Comment by ASnow** [comment]
Moved to https://github.com/json-schema-org/json-schema-spec/issues/102
