### ISSUE TITLE
Enum-controlled object types don't fail usefully.

### ISSUE THREAD

**Issue by stevage** [json-schema/json-schema#219]
I have a [biggish schema](https://github.com/TerriaJS/terriajs-schema/tree/master/schema/master). At its core, we have an array of objects, each of which is:

```
{
  "type": "foo",
  ...properties specific to the "foo" type
}
```

So to validate this, the schema looks like:

```
"items": {
    "type": "object",
    "title": "item",
    "allOf": [
      {
        "$ref": "CatalogMember.json"
      }
    ],
    "required": [
      "name",
      "type"
    ],
    "oneOf": [
      {
        "$ref": "JustCatalogGroup.json"
      },
      {
        "$ref": "BingMapsCatalogItem.json"
      },
      ...
```

and then each type has a schema with a specified enum value like this:

```
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "bing-maps"
      ],
```

In other words, at the top level we define that each object must be one of 20 schemas, and each schema defines an enum value and all the other properties.

This is capable of successfully validating data files. But when a file fails validaiton, we don't get any useful feedback, because the `oneOf` clause means that failures along the way are expected (object X is not type A, nor type B, nor type C...), so a failure only gets raised at the end when it failed to match anything at all.

So, my questions:
1. Is there a better way of doing this (in v4)?
2. If not, is there (or could there be) a proposal that would address this in v5?

In case this looks like an implementation issue, I'd suggest that my current way of implementing this schema feels like a hack - abusing the combination of `enum` and `oneOf` in this way. I'd much prefer to be able to directly say "if type='foo' then validate against foo.json, else ...".

**Comment by sam-at-github** [comment]
> But when a file fails validaiton, we don't get any useful feedback, because the oneOf clause means that failures along the way are expected (object X is not type A, nor type B, nor type C...), so a failure only gets raised at the end when it failed to match anything at all.

What's wrong with that exactly?

> In case this looks like an implementation issue, I'd suggest that my current way of implementing this schema feels like a hack - abusing the combination of enum and oneOf in this way. I'd much prefer to be able to directly say "if type='foo' then validate against foo.json, else ...".

Isn't that exactly what you doing??

As and aside, there is a proposal for a [constant](https://github.com/json-schema/json-schema/wiki/constant-%28v5-proposal%29) keyword for v5 which I'm definitely in favour of.

**Comment by sam-at-github** [comment]
You could also just do this type detection in logic outside of your json schema validator. I think I would lean that way?

**Comment by stevage** [comment]
>What's wrong with that exactly?

Well, maybe this is implementation specific, but when validating a schema like mine, you lose the context of the reason why a particular option failed, and only get an error like "none of these choices succeeded". This is ok-ish behaviour for `oneOf`, but just makes it painful for this use case.

>> I'd much prefer to be able to directly say "if type='foo' then validate against foo.json, else ...".
>Isn't that exactly what you doing??

No, the difference is if I *could* say "if X then validate Y", then any error in Y could instantly  be flagged, with context.

>You could also just do this type detection in logic outside of your json schema validator. I think I would lean that way?

Doing it outside the validator would be really hard, I think. Much more likely to just hack the validator.

Anyway, I think I have a workaround, which I haven't implemented yet, along these lines:
```
allOf`: [
  oneOf: [
    { type: "foo",
      properties: [ ... foo properties ] 
    }, {
       type: not "foo"
      }
    ]
]
```

That is, every object must be:

- all of:
  - one of:
    - not "type foo"
    - "type foo" (and related properties)
  - one of:
     - not "type bar"
     - "type bar" (and related properties)
 ...

If needed, I'll modify the validator to cause it throw an error when proceeding down the final branch of a `oneOf`. It doesn't need to climb back out of the validation tree, count the number of successes (0) and then report an error. If it has zero successes on its last attempt, it can throw immediately.

**Comment by epoberezkin** [comment]
how about using `switch` keyword?

**Comment by sam-at-github** [comment]
> No, the difference is if I could say "if X then validate Y", then any error in Y could instantly be flagged, with context.

Oh yeah of course. I don't think it implementation specific. You'd have to report all failures or none, neither are really what you want.

As @epoberezkin said, that is a UC for the  proposed `switch` keyword. if you do hack the validator your using then something like [switch](https://github.com/json-schema/json-schema/wiki/switch-%28v5-proposal%29) would work, but the syntax and semantics seem to be unsettled ATM - see #205.

What validator are you using?

**Comment by epoberezkin** [comment]
I was thinking about `switch` a lot actually as I was implementing it (I created this #205). The way I implemented is explained in [this algorithm](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#switch-v5-proposal).

**Comment by YurySk** [comment]
I also find that 'oneOf' and 'anyOf' do not lend themselves that well to error reporting. If a validator was to report errors on all schemas it would likely produce a whole lot of irrelevant errors, but reporting that the compositor-like error such as 'none are matched, therefor anyOf is not valid' is not great for troubleshooting. I don't think there's a good way too address it.
However, these keywords are really powerful, but they do come with a price.

**Comment by stevage** [comment]
Definitely straying into implementation now, but I wanted to mention that I recently added better error tracking to (a fork of) the JS json-schema validator [here](https://github.com/TerriaJS/jsonschema/commit/55cedb27a265bbae2b366a3824863c586c5d34cf).

There are some interesting semantic questions in working out what "the error" is when a multi-schema operator fails. I followed this:

- If nothing matches a `oneOf` or an `anyOf`, then every schema "failed", and the list of errors is the individual error that failed in each.
- If more than one thing matches a `oneOf`, then every schema that passed is in error - but you obviously can't point to a specific bit that passed that shouldn't have.
- If anything fails an `allOf`, then the first schema that fails is the error, so return the specific point at which it fails.

So in every case except the "too many successes for `oneOf`" you can point to at least one specific place in the schema that failed, which is much better than simply saying "something went wrong somewhere".

**Comment by handrews** [comment]
@stevage this repo is deprecated, and this topic is now being discussed at:
json-schema-org/json-schema-spec#31 
json-schema-org/json-schema-spec#64 (includes `switch`, formerly #25 here, plus alternatives)

Could you please close this issue (no one left with the project has the permissions needed to close it) and do any follow-up in the two issues in the new repo?  Thanks,
