### ISSUE TITLE
"unordered" keyword?

### ISSUE THREAD

**Issue by geraintluff** [json-schema/json-schema#22]
I've been thinking for a while about an "unordered" property for arrays.  This would default to false, and it would affect the rules for equality comparison as follows:

Instances would be considered equal if all the following conditions are true:
- both instances are arrays, and both instances are the same length
- all schemas describing both instances have the "unordered" keyword either undefined or set to be "true"
- for both instances, at least one schema describing that instance has the "unordered" keyword set to be "true"
- All items (in either instance) are equal (according to _(whatever)_) to the same number of items in both instances.

This is the kind of situation I'm thinking of - here, we have a list of unique schemas.

``` json
{
    "type": "array",
    "uniqueItems": true,
    "items": {"$ref": "http://json-schema.org/schema"}
}
```

Now, consider this instance:

``` json
[
    {
        "type": "object",
        "required": ["key1", "key2"]
    },
    {
        "type": "object",
        "required": ["key2", "key1"]
    }
]
```

Currently, that is valid.  But it shouldn't be - the schemas are basically the same.  However, if we declared the "unordered" flag on the "required" property of schemas, then the schemas in that list would be considered equal, and the above example would not validate.

**Comment by csaroff** [comment]
I can see that this is an extremely old issue, but what is the status of this keyword?  Is this closed as "won't standardize"?  I would definitely like to +1 this keyword.

**Comment by akuckartz** [comment]
This seems to be equivalent to the difference between a JSON-LD set and a JSON-LD list.

**Comment by csaroff** [comment]
For my use case, it is.  Is there a way to specify a set instead of a list in the json schema standard?  I hadn't been able to find it.
