### ISSUE TITLE
Clarify how custom errors should work for required fields...

### ISSUE THREAD

**Issue by the-t-in-rtf** [json-schema/json-schema#222]
The proposal for [custom error messages](https://github.com/json-schema/json-schema/wiki/Custom-error-messages-(v5-proposal)) is clear about customizing errors for field data that has been supplied but invalid.

We need an example of how required fields would be handled.  Required fields are defined in the enclosing element, as in this example:

```
{
  "properties": {
    "shallowlyRequired": {
      "type": "string",
      "properties": {
        "deeplyRequired": { "type": "string" }
      },
      "required": ["deeplyRequired"]
    }
  },
  "required": ["shallowlyRequired"]
}
```
My assumption is that the `errors` blocks in the above case might look something like:

```
{
  "properties": {
    "shallowlyRequired": {
      "type": "string",
      "properties": {
        "deeplyRequired": { "type": "string" }
      },
      "required": ["deeplyRequired"],
      "errors": {
        "required/0": "This field is required and I'm telling you about it from within a field definition."
      }
    }
  },
  "required": ["shallowlyRequired"],
  "errors": {
    "required/0": "This field is required and I'll tell you about it at the document level.",
    "shallowlyRequired/required/0": "This deep field is required."
  }
}
```

I'm happy to prepare a pull request if this seems reasonable.

**Comment by epoberezkin** [comment]
Sounds ok.
The paths in errors probably should be either a keyword or relative json pointers, so:

```
{
  "properties": {
    "shallowlyRequired": {
      "type": "string",
      "properties": {
        "deeplyRequired": { "type": "string" }
      },
      "required": ["deeplyRequired"],
      "errors": {
        "1/required/0": "This field is required and I'm telling you about it from within a field definition."
      }
    }
  },
  "required": ["shallowlyRequired"],
  "errors": {
    "1/required/0": "This field is required and I'll tell you about it at the document level.",
    "1/properties/shallowlyRequired/required/0": "This deep field is required."
  }
}
```

**Comment by epoberezkin** [comment]
difficult to implement though I think tracking errors from the outside, so I am not too fond of the idea to define errors outside of the object...

Maybe it should not be even the part of the standard...

**Comment by YurySk** [comment]
The errors messages need to be translated more often than not, i.e. this is a feature of a limited usefulness. 
I would much rather stipulate that a validator apis report errors in a granular enough way so the specific failing field can be easily determined by the calling program.

**Comment by erosb** [comment]
> I would much rather stipulate that a validator apis report errors in a granular enough way so the specific failing field can be easily determined by the calling program.

:+1: for this

**Comment by saibotsivad** [comment]
What is the benefit of the `error` field, compared to the already-existing `description` field?

Consider the following example:

```json
{
  "properties": {
    "someProperty": {
      "type": "string",
      "description": "A human-readable description of this property."
    }
  },
  "required": [ "someProperty" ]
}
```

If an API validating a JSON object finds the property `someProperty` missing, it would yield an error of some kind, and could use the `description` property of the schema in the error message.

**Comment by the-t-in-rtf** [comment]
@erosb and @saibotsivad, the v5 draft already has custom error messages in it.  I am arguing for clarifying how one type of rule is handled, but I'll take a minute to explain why (I feel) the new `errors` construct is definitely needed.

@saibotsivad, until I saw the v5 draft, I used the `description` field to provide more human-readable errors.  However, requiring schema authors to use that field for errors seems limiting. They cannot use the `description` field to (for example) describe to implementers the purpose of the field if they have to use the field for errors.  There is also no support for displaying schema or user-supplied data in descriptions, which is also part of the proposal.

Setting both of those aside for a minute, let's talk about internationalization and reusing schema material for a minute.  The draft v5 proposal gives an example of using document-level `errors` to define deep custom error messages at the document level.   This means that you can refer to material within another schema and then add or provide alternate error messages.  @YurySk, this could provide one approach to internationalization, i.e. you could have a `schema-jp.json` that wraps the material for `schema.json` and provides alternate error messages in Japanese.  It also provides a nice way to transition from v4 schemas to v5 compatibility, where you can add the new `errors` material without rewriting an existing remote schema that might not be under your control.

To answer @erosb, the reason this needs to be handled within an `errors` construct rather than by the validator is that it gives schema authors the ability to clarify their intent from within the schema.  Handling it by convention and requiring validators to take care of this work means you need presentation logic that interprets and generates a custom message based on the deep structure of the error. With the new `errors` block, you can reasonably expect to simply present the custom error message itself.  You could do something similar with `description` fields, but because these cannot be overridden or added at the document level, you would have less options in reusing schemas or internationalizing them as outlined above.

**Comment by the-t-in-rtf** [comment]
> difficult to implement though I think tracking errors from the outside, so I am not too fond of the idea to define errors outside of the object...

> Maybe it should not be even the part of the standard...

@epoberezkin, the document-level error mechanism is one of the key features of the proposal, IMO.  See my previous comments about the potential for internationalization.

**Comment by YurySk** [comment]
@the-t-in-rtf
Another thing about custom error messages that I struggle with is this: this mechanism seems to imply that upon any violation you get a fixed error message. I.e. no way to report a fine-grained condition. For instance, a maxLength violation or multipleOf. Usually when you track down a validation failure these kinds of messages are important. A blanket message I am afraid won't cut it in many cases.
About the only case when it will be more useful than a low level message is "pattern", since regex is not user friendly.

In my experience and admittedly biased opinion this type of parametrization is often not that useful since it has more to do with presentation than anything else. I do believe a well designed error api is more useful and it does not make any hidden assumptions in what a schema user will need. I.e. why, as a schema author, can I imply that a high-level blanket message should clobber a lower level diagnostics. I think this is up to the application to decide. In a form-type UI with per-field error display I definitely do need the low-level messages.

You can say its up to an implementer of a validation layer to deliver both messages via an api. The trouble is that this is a subtlety that many implementations will likely miss. I have been through that with XML and Xerses. You would think such a mature project would have these things sorted, but no, not at all. Providing a generic user-friendly error texts proved to be a project in its one due to the coarse nature of the api.
Obviously this is a very different case, it just goes to show that what is obvious to experienced people here is not obvious to others, differently experienced folks out there. I think the best way out of this is a clear separation of concerns. I.e. schema defines a data model and not the presentation specific to an implied use the model.
Just my humble opinion.

**Comment by the-t-in-rtf** [comment]
@YurySk, providing feedback on regular expression failures is a perfect example of why `error` blocks should be allowed within the JSON Schema.  

If a validator returns what it knows, things like what rule was broken and the underlying `pattern`, an implementer has no good way to convert that into a meaningful error message.  They can:

1.  Provide uselessly simplistic feedback like "invalid input".
2.  Provide feedback that is meaningless to end users, as in "must match ^[A-Z]$".
3.  Build their own mechanism for associating failing rules with more useful messages, and then painstakingly write their own messages for all failure cases in a schema (and any remote schemas).

It seems much more appropriate to allow a schema author to provide some hints that can be reused across a range of use cases.

I do agree that it shouldn't have to clobber the existing error output.

**Comment by the-t-in-rtf** [comment]
> Another thing about custom error messages that I struggle with is this: this mechanism seems to imply that upon any violation you get a fixed error message. I.e. no way to report a fine-grained conditions. For instance, a maxLength violation or multipleOf. Usually when you track down a validation failure these kinds of messages are important. A blanket message I am afraid won't cut it in many cases.
About the only case when it will be more useful than a low level message is "pattern", since regex is not user friendly.

@YurySk, In [the draft proposal for adding custom errors to v5](https://github.com/json-schema/json-schema/wiki/Custom-error-messages-(v5-proposal)), it's pretty clear that errors are defined with regard to the specific rule that is broken, as in this example taken from there:

```
{
  "properties": {
    "age": { "minimum": 13 },
    "gender": { "enum": ["male", "female"] }
  },
  "errors": {
    "#/properties/age/minimum": "Should be at least ${schema} years, ${data} years is too young.",
    "#/properties/gender/enum": {
      "text": "Gender should be ${schema/0} or ${schema/1}",
      "action": "replace"
    }
  }
}
```

**Comment by YurySk** [comment]
@the-t-in-rtf 
I have missed it so I stand corrected. Still think the whole thing is kinda heavy handed.

**Comment by claudio-viola** [comment]
I kind of  totally agree with all that @the-t-in-rtf  said in this conversation
Is this something that  will be considered to be done any time soon Or is there still discussions ongoing?

**Comment by handrews** [comment]
This and all other discussion of the custom errors proposal have been migrated to https://github.com/json-schema-org/json-schema-spec/issues/62
This issue should be closed (it is still linked from the new issue in the new repo).

**Comment by the-t-in-rtf** [comment]
Thanks to everyone who is picking up the governance work for the standard, it's much appreciated.  Happy to close this one out, see you in the new thread.
