### ISSUE TITLE
Relative JSON-pointer extension

### ISSUE THREAD

**Issue by epoberezkin** [json-schema/json-schema#223]
@geraintluff What do you think about extending [relative JSON-pointer](https://tools.ietf.org/html/draft-luff-relative-json-pointer-00) to be able to refer to the items in array with some relative position?

The syntax extension can be really simple, from the current N/JSONpointer to N+M/JSONPointer (to traverse N levels up and M items forward) or N-M/JSONPointer (M items backward), where N == 0 can possibly be dropped.

That would allow, for example, to implement restrictions on the array such as ascending/descending order (using `$data` [v5 proposal](https://github.com/json-schema/json-schema/wiki/$data-(v5-proposal))).

Ascending order without duplicates:

```JSON
{
  "type": "array",
  "items": {
    "type": "integer",
    "minimum": { "$data": "-1/" },
    "exclusiveMinimum": true
  }
}
```

Objects ordered in ascending order by unique `id` property:

```JSON
{
  "type": "array",
  "items": {
    "properties": {
      "id": {
        "type": "integer",
        "minimum": { "$data": "1-1/id" },
        "exclusiveMinimum": true
      }
    }
  }
}
```

**Comment by sam-at-github** [comment]
Seems like the only reason to define the new reserved word `$data` and not reuse `$ref` is to avoid a naming conflict with inline de-referencing?

Note my understanding of inline de-referencing is that given:

{
  foo: { id: foo }
  a: { $ref: "foo" }
  b: { $ref: "#/foo" }
}

foo, a, b all have the value `{ id: "foo" }` after deref. `{ $ref: "foo" }` being the inline deref. That is my reading of the spec. That section of the spec is a bit had to read, and ambiguous but I gathered it meant this since I've seen this type of referencing implemented.

**Comment by epoberezkin** [comment]
$ref is the reference to the schema, $data is the reference to the data being validated - see [v5 proposal](https://github.com/json-schema/json-schema/wiki/$data-(v5-proposal))

**Comment by YurySk** [comment]
Generally I like this proposal, the idea looks powerful.
However, I am a bit concerned about whether it would mandate a DOM-like in-memory handling. For example, if there's a forward reference, i.e. a reference to data that may be located further down in the document, the evaluation would require potentially the entire data model loaded in memory.
Same with references to data that was seen long ago, so a hypothetical parser buffer does not hold it anymore.

Am I barking up the wrong tree here? I do have number of cases when X gig json files are validated against the schema. With V4 it is possible with the exception of array item uniqueness.

**Comment by epoberezkin** [comment]
That concern equally applies to $data using relative JSON-pointer with or without the extension I proposed here - it can refer to any item with an absolute index anyway. This extension makes it more useful for array validation by allowing to refer to the next/previous items.

Validation of streamed data is an interesting thing, what validators implement it I wonder? In any case the problem you write about can be easily resolved in implementations (as long as the schema itself fits in memory) by pre-scanning the schema and storing required $data references.

**Comment by YurySk** [comment]
I am not aware of existing streaming implementations other the one I am working on. I am sure more are coming.
How about a dependency on a data that has not been read at. For example a large array that has a constraint referring to its last item or a property of an object following the array? Is that possible in the proposed model?
If so, you would not be able to validate items of the array immediately and would need to store all of them until you have the data needed for validation.

Isnt it in a way similar to XSLT formulas? These pretty much require the whole object model in memory.

**Comment by YurySk** [comment]
And yes, I suppose I am talking $data extension not the one you are talking specifically. Just wanted to verbalize my concerns.

**Comment by epoberezkin** [comment]
You'll have to defer the validation of the particular rule (and all the parent composite rules that depend on it) until the reference is resolved. It's a complication but it's doable.

**Comment by YurySk** [comment]
If it implies storing an unlimited amount of Json data until you hit the data needed for validation, it pretty much puts an end to streaming, does it not?

**Comment by epoberezkin** [comment]
I don't think it does put an end to streaming... You won't have to store unlimited amount of data, only the data that is used in $data and only until it's used.

There are two cases - 1) referenced data appears before $data. 2) $data appears before data it refers to.

The first case is relatively simple - you'll have to cache such data for a limited time (you'll need to preprocess the schema to know absolute paths you need to store and when you can discard those cached values).

The second case is a bit more involved. You'll have to defer the validation of the particular rule (and all the parent composite rules that depend on it) until the reference is resolved. It's a complication but it's doable. I implemented similar solution in a completely different context - it was about resolving references to unevaluated parts of a script in a [JSONScript](https://github.com/JSONScript/jsonscript) interpreter I am working on.

I completely agree that it is a complication. But then nobody can force you to support $data :). Streaming is a particular use case that is not very common. It's definitely interesting but I would start from breaking it into chunks and validated them separately... I expect that validating a stream as a single JSON object will impose some other limitations on the schema that can be used, so you most likely will support a subset of the standard anyway (as most validators do, especially when it comes to $ref resolution and IDs). So not supporting $data is not the end of the world, it's not even the part of the standard yet. I don't know any validator but my Ajv that currently supports it.

**Comment by epoberezkin** [comment]
> Streaming is a particular use case that is not very common.

I obviously didn't mean streaming as such. I meant streaming a large JSON object and processing it without waiting for the end of the object and without breaking it into limited size objects.

There are several keywords that will be quite challenging to implement in this scenario.

**Comment by YurySk** [comment]
My observation so far is that v4 lends itself nicely to streaming. One wrinkle is is array item uniqueness.
Beyond that the v4 spec aligns well with streaming, while supplying powerful and economical data paradigms. No need to store any data beyond a context of a streaming event, it's all about the decision tree you apply to the current piece of json data. The contexts are minimal, such as a number of properties seen so far, number of array items and validity state of subschemas under compositors like allOf.
That solution is easy to make performant and very easy on resources. I bet you that it can be ported into embdeeded devices and whatnot.
However, a need to store an arbitrary amount of data until a validation can be performed is a killer (correct me if I am wrong assuming this will be the case)

Sure, I don't have to support this feature and I won't because I support v4 only. However, it's nice to keep things simple and not introduce feature exemptions in the future. Makes for clearer communication and understanding between parties.

Anyway this is my 2.5 cents.

**Comment by epoberezkin** [comment]
$data usually refers to scalar/limited size data if it's any help. So i don't expect any large amount of data to be honest.

**Comment by YurySk** [comment]
In my experience if people can abuse s feature, they will :) If it up to me, I would define a feature in a way that doesn't make us use words 'usually' or 'typically' :) I prefer 100% clinical certainty :)

**Comment by handrews** [comment]
@epoberezkin could you close this to reduce the noise over here in deprecated-repo-land?  I know you already know where you can re-file it :-D

**Comment by epoberezkin** [comment]
Filed as https://github.com/json-schema-org/json-schema-spec/issues/115
