### ISSUE TITLE
Required and null

### ISSUE THREAD

**Issue by rsuter** [json-schema/json-schema#224]
I have this schema: 

	{
		"typeName": "ClassRoom",
		"additionalProperties": false,
		"type": "object",
		"required": [
			"Id"
		],
		"properties": {
			"Id": {
				"type": "integer"
			},
			"Name": {
				"type": "string"
			},
			"Size": {
				"type": "integer"
			}
		},
		"$schema": "http://json-schema.org/draft-04/schema#"
	}

And this data

    {
        "Id": 1,
        "Name": "First",
        "Size": null
    }

The question here is with the Size property: Can it be null when it is not required or is this invalid? http://jsonschemalint.com/draft4/ shows a validation error... Is this correct?

**Comment by epoberezkin** [comment]
Yes. You can `"Size": { "type": ["integer", "null"] }

**Comment by handrews** [comment]
@rsuter could you please close this?  This repo is deprecated and non one still with the project has the permissions needed to close out old issues.  Thanks!

**Comment by rsmckinney** [comment]
This looks wrong.  Applying simple logic, if a property is not `"required"` and has no `"default"` value defined, its initial value is null (or undefined) if not explicitly assigned.  Thus these two documents have the same effect:

```json
{
    "Id": 1,
    "Name": "First"
 }
```
```json
{
    "Id": 1,
    "Name": "First",
    "Size": null
}
```
But the second one is illegal, which doesn't make much sense.

In my view `"required"` should have broader meaning to imply _not null_ and dispense with the awkward `"null"` type, perhaps replace it with a simpler `"nullable"` attribute.
