### ISSUE TITLE
strictProperties for date-time formatMinimum and formatMaximum

### ISSUE THREAD

**Issue by MosleyWilliams** [json-schema/json-schema#225]
I'm having problems with Json Schema when I'm trying to validate date-time value between interval of time [2013-11-17T00:00Z, 2015-11-17T00:00Z] I have this Json Schema:

```
{
  "strictProperties": true ,
  "type": "object",
  "properties": {
    "data": {
      "type": "object",
      "properties": {
        "exampleDate": {
          "format": "date-time",
          "formatMinimum": "2013-11-17T00:00Z",
          "formatMaximum": "2015-11-17T00:00Z"
        }
      }
    }
  },
  "required": [
    "data"
  ]
}
```

And with this json always out is as valid json:

```
{
    "data": {
        "exampleDate": "2010-11-17T00:00:00Z"
    }
}
```

But as you can see, this json is not valid because of the date, it is out of valid range.

I've tested in online tools http://www.jsonschemavalidator.net/, http://jsonschemalint.com/draft4/# and with com.github.fge:json-schema-validator:2.2.6. Could someone help me please? Maybe I missing some configuration besides strictProperties? some step?. Thanks in advance =)

**Comment by Clemens-U** [comment]
Hi,

I'm afraid the formatMaximum and formatMinimum keywords are simply ignored
by json-schema-validator:2.2.6 engine because I get the following warnings
in XML ValidatorBuddy on validating the JSON schema:


​
And the tool uses json-schema-validator:2.2.6 currently.

Hope this helps
Clemens



2016-03-03 20:22 GMT+01:00 Mosley <notifications@github.com>:

**Comment by MosleyWilliams** [comment]
Then with json-schema-validator:2.2.6 is not working, but only with Json Schema is it?. Actually I'm confused if v5 strictProperties is already available to use, or will be released as other version of JsonSchema?.
In the other hand, then you think any tool for Java will work as expected for this restrictions (formatMaximum, formaMinimum)? just in case do you know some tool which works as expected? Regards

**Comment by jdesrosiers** [comment]
@MosleyWilliams, there is no v5 yet.  At this point there are a bunch of proposals, but no decisions about what will make the cut.  The latest draft of JSON Schema is not capable of what you are trying to do.  Specifically from your example: `strictProperties`, `formatMinimum`, and `formatMaximum` are not part of the JSON Schema spec.  They might be at some point in the future, but not yet.  There might be validators out that implement things like this, but I would guess that most will wait until the behavior is standardized.

**Comment by MosleyWilliams** [comment]
Now is clear to me, @Clemens @jdesrosiers thank you so much for help =)

**Comment by clemens** [comment]
You tagged the wrong Clemens, bro. :)

**Comment by MosleyWilliams** [comment]
I have other question please, about date-time oficial format for json schema v4. I found oficial format for v3 (here https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23), where it is 
YYYY-MM-DDThh:mm:ssZ in UTC time, Can I assume that this format continues been using in v4? Because I didn't found which format should I follow for v4 in its documentacion, or maybe I miss some docs?. Could someone help me please? thanks in advance

**Comment by Clemens-U** [comment]
I can show you the output from the JSON schema validator
com.github.fge:json-schema-validator:2.2.5 which is actually a reference
implementation and standard compliant with draft4. Here you see what the
validator expects:


​
Hope this helps
Clemens


2016-03-04 16:16 GMT+01:00 Mosley <notifications@github.com>:

**Comment by MosleyWilliams** [comment]
@Clemens-U you mean this json schema validator? http://json-schema-validator.herokuapp.com/ (v4), with this one seems the expected format is YYYY-MM-DDThh:mm:ssZ

**Comment by jdesrosiers** [comment]
date-time uses RFC-3339.  This is from the current (draft-04) specification.

> A string instance is valid against this attribute if it is a valid date representation as defined by [RFC 3339, section 5.6](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14)
> * http://json-schema.org/latest/json-schema-validation.html#anchor108

**Comment by Clemens-U** [comment]
Hi Mosley,

yes. This one also uses the validator from
https://github.com/fge/json-schema-validator


2016-03-04 20:45 GMT+01:00 Mosley <notifications@github.com>:

**Comment by Zilev** [comment]
Hi @jdesrosiers , @Clemens-U , one question about this date format v4 which follows ISO 8601 ( https://en.wikipedia.org/wiki/ISO_8601), I've playing with this validator http://json-schema-validator.herokuapp.com/ with this examples:

> Date:	2016-03-05
> Combined date and time in UTC:	2016-03-05T06:24:57+00:00
> 2016-03-05T06:24:57Z
> 20160305T062457Z
> Week:	2016-W09
> Date with week number:	2016-W09-6
> Ordinal date:	2016-065

But only accepts as valid format date this examples:

> Combined date and time in UTC:	2016-03-05T06:24:57+00:00
> 2016-03-05T06:24:57Z

The other ones shows as invalid. Is ok this behaviour? I though as all of those examples are expressed according to ISO 8601 all of them should be accepted as valid. Maybe I misunderstood something? Thanks in advance.

**Comment by jdesrosiers** [comment]
The JSON Schema draft-04 defines date-time as [RFC 3339, section 5.6](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14).  This references ISO 8601, but my understanding is that it is only the subset of ISO 8601 defined as "date-time" in section 5.6.

**Comment by Zilev** [comment]
@jdesrosiers I see, then this examples:

```
2016-03-05T06:24:57+00:00
2016-03-05T06:24:57Z
20160305T062457Z
```
which are following this format explain in RFC 3339, section 5.6:

>    date-fullyear   = 4DIGIT
>    date-month      = 2DIGIT  ; 01-12
>    date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on
>                              ; month/year
>    time-hour       = 2DIGIT  ; 00-23
>    time-minute     = 2DIGIT  ; 00-59
>    time-second     = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second
>                              ; rules
>    time-secfrac    = "." 1*DIGIT
>    time-numoffset  = ("+" / "-") time-hour ":" time-minute
>    time-offset     = "Z" / time-numoffset
> 
>    partial-time    = time-hour ":" time-minute ":" time-second
>                      [time-secfrac]
>    full-date       = date-fullyear "-" date-month "-" date-mday
>    full-time       = partial-time time-offset
> 
>    date-time       = full-date "T" full-time

I think should be validated as ok. The first one and second are working as expected, but the last is not. The validator shows failure:

```
[ {
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : "/properties/metadata/properties/editorial.release_date"
  },
  "instance" : {
    "pointer" : "/metadata/editorial.release_date"
  },
  "domain" : "validation",
  "keyword" : "format",
  "attribute" : "date-time",
  "message" : "string \"20160305T062457Z\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]",
  "value" : "20160305T062457Z",
  "expected" : [ "yyyy-MM-dd'T'HH:mm:ssZ", "yyyy-MM-dd'T'HH:mm:ss.SSSZ" ]
} ]
```

Then making a summary of date format that explained in RFC 3339, section 5.6, can I assume the only date formats accepted by json schema and json schema validator are** [ "yyyy-MM-dd'T'HH:mm:ssZ", "yyyy-MM-dd'T'HH:mm:ss.SSSZ" ]**

**Comment by fge** [comment]
@Zilev 

> The first one and second are working as expected, but the last is not.

Of course it is not!

The '-' is **SIGNIFICANT** in the format. Read the grammar again.

**Comment by jdesrosiers** [comment]
Your third example doesn't look like it matches the specification.  The separators are not optional (see "full-date" and "partial-time").  I can't speak for the precise behavior of json-schema-validator, but it sure looks like it's telling you exactly what it expects.

**Comment by Zilev** [comment]
@jdesrosiers now I get it, thanks a lot for helping me =)

**Comment by fge** [comment]
@jdesrosiers indeed, the separators are not optional; I coded the validator to be as picky as I am, and that is saying all of it, really :p

**Comment by Zilev** [comment]
:smile: :smile: :smile: :smile:

**Comment by handrews** [comment]
@MosleyWilliams Since there hasn't been any activity here for months could you please close this issue?  This repo is deprecated and there is no one with the project who has the permissions to close all of the old open issues.

Please feel free to file new issues (or re-open this) at the new json-schema-spec repo.
