### ISSUE TITLE
[Proposal] Improving date-time: min/max, linking & step

### ISSUE THREAD

**Issue by Lcfvs** [json-schema/json-schema#227]
Hi,

Just to suggest a min/max equivalent for date-time fields (min/max, begin/end, ...).

It may be useful to indicate a date time range, like for a reservation vs availability, an event beginning/end.

Imho, it may be also useful to link it to an another date-time field, with a positive/negative step.

What do you think about it?

**Comment by handrews** [comment]
@Lcfvs I've migrated this issue to the new repo.  Could you please close this one?  No one remaining with the projects has the ability to close issues filed by other people.
