### ISSUE TITLE
oneOf implicit validation

### ISSUE THREAD

**Issue by zanona** [json-schema/json-schema#229]
I have been trying to understand `oneOf` as we as `allOf` but am failing to learn why there's the need to explicitly cause an element to fail in order to trigger these features.

The example below is related to `oneOf` but the same concept can be applied to `allOf`

**schema** _using js for readability_

``` js
{
    oneOf: [
        { properties: { a: { type: 'string', minLength: 3 }}},
        { properties: { b: { type: 'string', minLength: 3 }}},
        { properties: { c: { type: 'string', minLength: 3 }}}
    ]
}
```

**documents validated against the schema above:**

``` js
{ } // All valid (even when not providing any property with string longer than 3 chars)
{ a:  "abc" } // All valid
{ a:  "abc",  b: "abc" } // All valid
{ a:  "abc",  b: "abc", c: "abc" } // All valid
```

Surprisingly it seems that there's the need to explicitly cause the validation to fail:

``` js
{ a: "a" }  //`b` and `c` are valid, not triggering oneOf
{ a:  "a", b: "b" } //`c` is valid, triggers oneOf even though `c` is not present
```

So I am failing to understand how is not providing properties at all, when the schema is explicit about requiring string with a minimum of 3 characters, valid? The same could happen with numbers instead where requiring numbers larger than 5 and an empty document would still be a valid case?

> It may be also important to mention that by setting items in the array of `oneOf` as **required**, would in this case, cause one of the properties to be required which is not the intended behaviour. The idea would be to keep the `a`, `b`, and `c`, optional, however only accepting one of them if present.

Perhaps I am missing something. It would be a great help if this could be somehow clarified?

Thanks in advance

**Comment by erosb** [comment]
Which implementation are you using?

**Comment by zanona** [comment]
@richievos I am validating with [AJV](https://github.com/epoberezkin/ajv) which uses Draft-4 by default. However, I have tried other validators and apparently all of maintain the same behaviour?

It's possible to test from this snippet:

https://tonicdev.com/zanona/56f9605ac4ffa41100ab3b37

**Comment by epoberezkin** [comment]
`oneOf`, by definition, will succeed when one and only one schema is valid.
`anyOf` requires one or more schemas to be valid.
`allOf` requires all schemas to be valid.

You can think about them as being equivalent to logical XOR, OR and AND.

Regarding the schema requiring a string, `properties` keyword does not require any property to be present. It requires that IF the property is present then to be valid its value should be valid according to the schema. If you want to require the property to be present there is `required` keyword for that.

Maybe this [keywords reference](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md) can be helpful.

**Comment by epoberezkin** [comment]
If what you are trying to achieve is that the object should only have one property, be it `a`, `b` or `c` then this schema will do it:

```javascript
{
  properties: {
    a: { type: 'string', minLength: 3 },
    b: { type: 'string', minLength: 3 },
    c: { type: 'string', minLength: 3 }
  },
  oneOf: [
    { required: ['a'] },
    { required: ['b'] },
    { required: ['c'] }
  ]
}
```

**Comment by zanona** [comment]
@epoberezkin Thanks a lot for your explanation. — and also for the awesome validator (AJV)

Just to make sure I understand: once supplying `oneOf` with different properties as per the example I have supplied, the schema will be validated against `properties` itself and not the result of what happens inside the declaration like, `minLength: 3`, etc. Hence, as per your response, an empty object would still be valid? Is there any use case where `eachOf` with a set of `properties` would apply? Because in this case it would always return true when not provided correct and more appropriately used with parameters other than `properties`?

---

Also, thanks a lot for the example supplied, it is indeed much cleaner.
However, the example would make it compulsory that one of `a`, `b`, or `c` are provided correct?
Is there any way to make them optional so when provided, it has to be only one of either `a`, `b`, or `c` respectively, but at the same time allow documents without any of these properties to still be valid?

So in this case a document with `{ anotherProperty: 'text' }` would still validate.

My first thought was:

```js
  oneOf: [
    { required: [   ] },
    { required: ['a'] },
    { required: ['b'] },
    { required: ['c'] }
  ]
```
But then, `required` must have at least one element.

**Comment by epoberezkin** [comment]
Thanks.

> an empty object would still be valid

yes

> the example would make it compulsory that one of a, b, or c are provided

yes

> Is there any way to make them optional?

There are several ways, e.g.

```javascript
{
  oneOf: [
    { not: {
      anyOf: [
        { required: ['a'] },
        { required: ['b'] },
        { required: ['c'] }
      ]
    } },
    { required: ['a'] },
    { required: ['b'] },
    { required: ['c'] }
  ]
}
```

Probably there is more elegant way to achieve it.

**Comment by epoberezkin** [comment]
E.g. with `patternRequired` (v5 proposal):

```
{
  oneOf: [
    { not: { patternRequired: [ '^(a|b|c)$' ] } },
    { required: ['a'] },
    { required: ['b'] },
    { required: ['c'] }
  ]
}
```

**Comment by epoberezkin** [comment]
or

```javascript
{
  oneOf: [
    { properties: {
      a: { not: {} },
      b: { not: {} },
      c: { not: {} }
    } },
    { required: ['a'] },
    { required: ['b'] },
    { required: ['c'] }
  ]
}
```

or

```javascript
{
  oneOf: [
    { patternProperties: { '^(a|b|c)$': { not: {} } } },
    { required: ['a'] },
    { required: ['b'] },
    { required: ['c'] }
  ]
}
```

**Comment by epoberezkin** [comment]
Actually, `{ required: ['a'] }` is equivalent to `{ not: { properties: { a: { not: {} } } } }`

Interesting.

**Comment by zanona** [comment]
thanks a lot @epoberezkin, it's indeed an interesting logic. I have never thought about nesting `eachOf`, `not` and `anyOf` statements. It really does the job :)

I do think it could be of great importance to perhaps [clarify a little bit](https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not) how schemas would interpret these statements when used against `properties`, so it's intuitive and easier to understand as a newcomer?

But thanks again for your insightful examples.

All the best

**Comment by handrews** [comment]
@zanona :  This repo has been abandoned by the admins so no one can do anything like close issues here.  Could you please close this issue yourself?

If you'd like to see more clarification, please file an issue at [json-schema-org/json-schema-org.github.io](https://github.com/json-schema-org/json-schema-org.github.io) which is the new web site repo (the spec is the json-schema-spec repo within that organization).
