### ISSUE TITLE
In my JSON data (the actual payload), how do I indicate which JSON schemas to use?

### ISSUE THREAD

**Issue by mwherman2000** [json-schema/json-schema#235]
In my JSON data (the actual payload), how do I indicate which JSON schemas to use for either a) the entire payload and/or b) the schema to use for specific properties with an object?

I see examples of JSON objects and JSON schema but I haven't found an example of JSON object being tagged with the appropriate list of schemas that should be used to validate the object.

Thank you,
Michael Herman (Toronto)

**Comment by mwherman2000** [comment]
I found a partial/workable/working answer here: https://github.com/json-schema/json-schema/issues/220#issuecomment-209452992

...even if it doesn't appear to be a universally accepted approach.

**Comment by robbie-mac** [comment]
@mwherman2000 
As I said in the referenced thread, data is meaningless without context. Your application logic creates that context. One of the ways you can leave hints for your context is to have a custom file extension, or even a custom file/stream header.
Im sure there are other solutions, but your use case will dictate the best solution, and its up to you as the developer to find it. If you wait for a universally accepted solution you might be waiting a long time.

**Comment by Acubed** [comment]
One of the documented methods is the "profile" media parameter:

```
Content-Type: application/json;profile="http://example.com/schema.json"
```

The other is a link. In HTML you would do this like `<a href="http://example.com/schema.json" rel="profile"></a>"` or `<link rel="profile" href="http://example.com/schema.json"/>` Here's how you would specify a link using the HTTP Link header:

```
Link: <http://example.com/schema.json>;rel="profile"
```

However, neither of these entirely fit within established convention. The "profile" link relation explicitly says that the target of the link isn't necessarily an information resource and clients should not dereference it.
