### ISSUE TITLE
Feedback: Disappointingly incomplete set of primitive types

### ISSUE THREAD

**Issue by mwherman2000** [json-schema/json-schema#237]
Reference: http://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.5

One of my goals for JSON is data interchange between like as well as disparate systems (e.g. between 2 SQL Servers or SQL Server and Oracle).  It's disappointing to see that the set of primitive types in the Core Specification is incomplete ...that I can't can't complete describe the schema for a SQL Server table, for example, because of missing types.

Here's a table that summarizes/illustrates the problem: https://msdn.microsoft.com/en-ca/library/dn921899.aspx

Once a SQL Table has been serialized into JSON and JSON-Schema, apparently there is not enough information to be able to recreate the SQL Table.  It's these sort of shortcomings that drive people to use fields like the description property to encode the missing capabilities.

Best regards,
Michael Herman (Toronto)

**Comment by erosb** [comment]
The primitive types are defined by JSON and not JSON Schema, therefore I
don't see the reason why you report it. Secondly, the JSON Schema spec
permits additional properties in schema objects, and additional properties
(at any level) can be used to encode any kind of information, therefore
usecases not supported by the JSON Schema can be simply described. Using
"description" for this purpose is just a stupid idea.

Furthermore issues exist for the purpose of bugreports and feature
requests, and not for whining.

Congrats @mwherman2000 , this was the most stupid issue I've ever read on
github.

2016-04-19 9:51 GMT+02:00 mwherman2000 <notifications@github.com>:

> Reference: http://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.5
>
> One of my goals for JSON is data interchange between like as well as
> disparate systems (e.g. between 2 SQL Servers or SQL Server and Oracle).
> It's disappointing to see that the set of primitive types in the Core
> Specification is incomplete ...that I can't can't complete describe the
> schema for a SQL Server table, for example, because of missing types.
>
> Here's a table that summarizes/illustrates the problem:
> https://msdn.microsoft.com/en-ca/library/dn921899.aspx
>
> Once a SQL Table has been serialized into JSON and JSON-Schema, apparently
> there is not enough information to be able to recreate the SQL Table. It's
> these sort of shortcomings that drive people to use fields like the
> description property to encode the missing capabilities.
>
> Best regards,
> Michael Herman (Toronto)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/json-schema/json-schema/issues/237>
>



-- 


*Bence Erősme@github <https://github.com/erosb>*

**Comment by mwherman2000** [comment]
Carry on in your JSON bubble

**Comment by YurySk** [comment]
You can't possibly expect JSON (or XML) to support all binary representations that a particular database or system uses. I work with mainframes and it has a number of formats most people have not heard about. They come with their own set of constraints and attributes that typically cannot be expressed in a single word such as 'float'.
Our XML based software uses non-schema attributes to describe these aspects. Exact same approach can be used in json-schema and JSON.

**Comment by mwherman2000** [comment]
(Seriously) Not to stir this pot any more and only out of curiosity I took one of my larger JSON payloads, converted it to XML, loaded it to an ADO.NET DataSet (to auto generate a schema using a DataSet's schema-by-example capability), then converted the XSD XML back to JSON to get an JSON version of the custom XSD schema.  First of all it actually worked and second, it's almost usable but not really.  The show stopper is that JSON Values are quoted strings ...so guess which datatype(s) schema-by-example produces: all strings. :-)   Here's a (longish) sample:

{
  "?xml": {
    "@version": "1.0",
    "@standalone": "yes"
  },
  "xs:schema": {
    "@id": "entities",
    "@xmlns": "",
    "@xmlns:xs": "http://www.w3.org/2001/XMLSchema",
    "@xmlns:msdata": "urn:schemas-microsoft-com:xml-msdata",
    "xs:import": {
      "@namespace": "http://james.newtonking.com/projects/json",
      "@schemaLocation": "export2.schema_app1.xsd"
    },
    "xs:element": {
      "@name": "entities",
      "@msdata:IsDataSet": "true",
      "@msdata:UseCurrentLocale": "true",
      "xs:complexType": {
        "xs:choice": {
          "@minOccurs": "0",
          "@maxOccurs": "unbounded",
          "xs:element": {
            "@name": "entity",
            "xs:complexType": {
              "xs:sequence": {
                "xs:element": [
                  {
                    "@name": "created",
                    "@type": "xs:string",
                    "@minOccurs": "0",
                    "@msdata:Ordinal": "0"
                  },
                  {
                    "@name": "source",
                    "@minOccurs": "0",
                    "@maxOccurs": "unbounded",
                    "xs:complexType": {
                      "xs:sequence": {
                        "xs:element": [
                          {
                            "@name": "timestamp",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ipv4Address",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ipv6Address",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "hostName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          }
                        ]
                      }
                    }
                  },
                  {
                    "@name": "processingHistory",
                    "@minOccurs": "0",
                    "@maxOccurs": "unbounded",
                    "xs:complexType": {
                      "xs:sequence": {
                        "xs:element": [
                          {
                            "@name": "timestamp",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "hostName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "applicationComponent",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          }
                        ]
                      }
                    }
                  },
                  {
                    "@name": "payload",
                    "@minOccurs": "0",
                    "@maxOccurs": "unbounded",
                    "xs:complexType": {
                      "xs:sequence": {
                        "xs:element": [
                          {
                            "@name": "RowNumber",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "DeviceNumber",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ActivationRequired",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "AccountExpires",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "AdDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "AdDnsHostName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "AdDomainName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "AdFullyQualifiedDomainName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "AdOsVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "AdminPasswordStatus",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BiosCharacteristics",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BiosManufacturer",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BiosName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BiosReleaseDate",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BiosSerialNumber",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BiosVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BootDevice",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BootRomSupported",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BuildNumber",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "BusType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ChassisBootUpState",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ComputerSystemName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "CountryCode",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "CreateCollectorId",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "CreateDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "CreationDate",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "CsdVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "CurrentLanguage",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "CurrentTimeZone",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "DayLightInEffect",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Debug",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Description",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "DistinguishedName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "DnsHostName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "DomainRole",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Drive",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "EnableDaylightSavingsTime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "EnclosureManufacturer",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "EnclosureSerialNumber",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "FreePhysicalMemory",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "FreeSpaceInPagingFiles",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "FreeVirtualMemory",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "FrontPanelResetStatus",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "HostNameForVm",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "InfraredSupported",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "InsertState",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "InstallableLanguages",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "InventoryRowversion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "InventoryWatermark",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "KeyboardPasswordStatus",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "LargeSystemCache",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "LastBootupTime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "LastLogonTimestamp",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "LastUserLogon",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "LocalDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Locale",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "LockPresent",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "MaxNumberOfProcesses",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "MaxProcessMemorySize",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "MaximumSize",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Model",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "MuiLanguages",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NetworkServerModeEnabled",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NumberOfCores",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NumberOfLicensedUsers",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NumberOfLogicalProcessors",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NumberOfProcessors",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NumberOfUsers",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ObjectGuid",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OperatingSystem",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OperatingSystemServicePack",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OperatingSystemSku",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Organization",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsArchitecture",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsBuildType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsCaption",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsCodeset",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsInstallDate",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsLanguage",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsManufacturer",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "OsProductSuite",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PartOfDomain",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PauseAfterReset",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PcSystemType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PowerOnPasswordStatus",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PowerState",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PowerSupplyState",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PrimaryBios",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PrimaryFlag",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PrimaryOwnerName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ProductId",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ProductType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "QuantumLength",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "QuantumType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "PwdLastSet",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "RegistryDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "RegistryScanResult",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "RegisteredUser",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "RemainingEvaluationPeriod",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "RemainingGracePeriod",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ResetCapability",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ResetCount",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ResetLimit",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Roles",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SecurityStatus",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SerialNumber",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ServerName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ServicePackMajorVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "ServicePackMinorVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SiteName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SmbiosAssetTag",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SmbiosBiosVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SmbiosMajorVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SmbiosMinorVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SmbiosPresent",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SuiteMask",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SystemDevice",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SystemDirectory",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SystemDrive",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SystemStartupDelay",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SystemType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "TotalPhysicalMemory",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "TotalVirtualMemorySize",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "TotalVisibleMemorySize",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "UpdateCollectorId",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "UpdateDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "VmFriendlyName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WakeupType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WindowsDirectory",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiChassisTypes",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "SshScanResult",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiDnsHostName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiDomainName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiProductType",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiOsVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiScanResult",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WmiScanResultDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "UserName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NetServerEnumDomainName",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "NetServerEnumOsVersion",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WinNetworkCollector",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "WinNetworkDatetime",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          },
                          {
                            "@name": "Workgroup",
                            "@type": "xs:string",
                            "@minOccurs": "0"
                          }
                        ]
                      }
                    }
                  }
                ]
              },
              "xs:attribute": { "@ref": "app1:schema" }
            }
          }
        }
      }
    }
  }
}

**Comment by YurySk** [comment]
I am not understanding the issue. Why quoted strings are an issue?

**Comment by mwherman2000** [comment]
I'm not presenting it as an issue.  It's just the way DataSet schema-by-example works and the fact the JSON Values are quoted.  They don't play well together (and weren't expected to).

Is there a better discussion forum to these sorts of more general JSON Schema discussions?

**Comment by YurySk** [comment]
Still, can you elaborate why quoted strings are a problem for you?

**Comment by mwherman2000** [comment]
Because DataSets are  (apparently) dumb about quoted strings.  Anything that is a quoted string appears to be typed as an xs:string ...e.g. even datetime, integers, guids, etc.  (This is a non JSON conversation at this point.)

**Comment by YurySk** [comment]
Ok. Just a quick comment: numerics are not quoted in JSON. If they are surrounded by quotes they are strings even in JSON sense.

**Comment by fge** [comment]
@YurySk  and the same goes for booleans.

@mwherman2000 one thing you don't seem to understand about JSON Schema is that it only cares about JSON, as in RFC 7159. And JSON defines only 4 primitive types: string, number, boolean and null. Nothing else. JSON Schema also defined integer, thought, which is a strict subset of numbers (a JSON number without any decimal part or exponent).

What you do with that JSON afterwards is simply out of scope and implementation specific. JSON Schema will not go there. 

Not its core spec, at least. After that, you can define your own keywords which do whatever you like. Even tell whether a value is valid only between Monday and Tuesday. Whaever.

**Comment by YurySk** [comment]
@fge

...and null :)

**Comment by robbie-mac** [comment]
@mwherman2000 
So to summarize your large payload exercise:
You took a large dataset in JSON,  translated it using a few general purpose translators, round trip back to JSON, and are surprised you got a different result? Ever played telephone as a kid?

Although I can understand where @erosb is coming from, I'll try to put it in a more constructive manner. The purpose of a schema is to define form not function. Function is defined by the logic built into the application. Said another way, each use case requires its own unique processing logic, or in your case, translating logic. All the schema will do is define the list of properties that each data fragment will have. If you have a mysql char for instance you need to define a char object with a tyle of string and a maxlength of 1. Now you want varchar? No problem, specify an array of char type. Yes its a little bit of work, and then you still have the work of your logic, and how you want to map native types to your intermediary types because you will never achieve a 1 to 1 parity, but thats programming. If it was easy everybody would be doing it.

**Comment by mwherman2000** [comment]
First, my apologies for introducing several (related) issues with this one thread ...but I think I've found a reasonable solution for representing the SQL Server type system (or any non-JSON type system) using JSON-Schema.  

Looking at the schema for JSON-Schema, as an example, (http://json-schema.org/draft-04/schema#), I think the trick/best practice will be to mechanically add a JSON-Schema *definition* for each of the known SQL Server data types, and then in the *properties*, simply $ref the appropriate SQL Server type by the name of its definition.   Very simple.  Very mechanical to generate.  Thoughts?

Michael Herman (Toronto)

**Comment by robbie-mac** [comment]
@mwherman2000
Close, but not quite. You are mixing schema and data.
Take your first line as an example:
""sql_bigint : { type : "number", sql_typeid : 0, base64encoded : false },""

**Comment by mwherman2000** [comment]
@robbie-mac, in SQL Server, each SQL Server data type also has a documented unique numerical "ID" ...this is what I'm storing in the "sql_typeid" property of the schema. ...it's like a numerical alias for the "sql_xxxx" name.

p.s. I've updated my previous sample with proper quoting.

**Comment by robbie-mac** [comment]
@mwherman2000 
If I was to deal with this problem myself, I would have 2 data files and at least 2 schema. 1 data file is the list of SQL types, and can be validated by an SQLTypes schema. Then I would have my actual data, that validates against another schema.
That way if your use/understanding/or the SQL version introduces another type or deprecates a type, then I would only have to update 1 file. Not the schema, and any other data sets I had.
This way, you don't expose the logic or methods of your application in the data that you might have to share back and forth with other applications.
As I said before though. Its your application, and only you can decide what is best.
However, I don't think the way you are going about it could be called a "best practice" where this spec is concerned, just your application.

Regardless, I am going to suggest this issue be closed. If you want to discuss it further fine, but in the context of it being an issue for the spec, I think it has played out and can be closed.

**Comment by mwherman2000** [comment]
This can be closed.  As a final foot note, checkout the the following tech note.  This gives you an idea of where I am headed: [https://hyperonomy.com/2016/04/26/parallelspace-team-iot-json-message-formats/](https://hyperonomy.com/2016/04/26/parallelspace-team-iot-json-message-formats/)

Michael Herman (Toronto)

p.s. I think there is an outstanding issue of how to transport/embed a JSON-Schema inside a parent JSON object (for the reasons I mentioned above).  The intended effects are: a) to actually send or transport a schema as an embed in a parent JSON object (without having to Base64 encode it, for example) and b) to create self-describing/self-documenting JSON objects (e.g. an object that includes a copy of its object type schema).
