### ISSUE TITLE
Embedding JSON-Schema objects as a child object breaks $ref locations

### ISSUE THREAD

**Issue by mwherman2000** [json-schema/json-schema#239]
Checkout this example: [JSON-Schema sample for SQL Server](https://hyperonomy.files.wordpress.com/2016/04/sql-json-sample.png)

I started using the following business-as-usual format for the $ref location in my JSON-Schema:

"DeviceNumber": { "$ref": "#/definitions/sql_uniqueidentifier" },

But I then need to embed the schema object as a child object inside a parent JSON object.  This broke the $ref locations.  To get the JSON to validate, I needed to change the $ref location to: (see the diagram above)

"DeviceNumber": { "$ref": "#/**payload/event/**definitions/sql_uniqueidentifier" },

Is there a way to specify the $ref location in relative terms? ...e.g. using dot-dot notation?  For example, I couldn't get the following to work:

"DeviceNumber": { "$ref": "../../definitions/sql_uniqueidentifier" },
 
Best regards,
Michael Herman (Toronto)

**Comment by cbandy** [comment]
https://tools.ietf.org/html/rfc6901#section-4

> ```
   Evaluation of a JSON Pointer begins with a reference to the root
   value of a JSON document and completes with a reference to some value
   within the document.
```

**Comment by robbie-mac** [comment]
@mwherman2000 
Michael, this may seem belittling but you may want to read the guide at the following link:
[http://spacetelescope.github.io/understanding-json-schema/](url)
From your other comments, and from the example image you posted in this comment, leads me to believe the guide may be your best resource for a while.

You have several out of place key/value pairs:
You keep putting instance values inside your schema.
I will provide a simple example below, but I think you might want to try a few basic exercises before you bet the farm on this in a production application.

**Remember: A schema describes/defines the form of your end data, your end data contains values. These are separate objects.**

example-schema.json
```
{
   "$schema" : "http://json-schema.org/draft-04/schema#",
   "id" : http://esample.com/example-schema.json",
   "description" : "Example schema, describing example data",
   "type" : "object",
   "properties" : {
      "list" : {
         "type" : "array",
         "items" : {
            "type" : "object",
            "properties" : {
              "field1" : {
              "type" : "string"
            },
            "field2 : {
               "type" : "integer"
            }
         }
      }
   }
}
```
example-data.json
```
{
   "list" : [
      {
         "field1" : "my data string",
         "field2" : 5
      },
      {
         "field1" : "Answer to the question of life, the universe, and everything.",
         "field2" : 42
      }
   ]
}
```

**Comment by handrews** [comment]
see also https://tools.ietf.org/html/draft-luff-relative-json-pointer-00 for a JSON Pointer extension that would handle this.  It's an expired draft, but so is JSON Schema :-)

**Comment by erosb** [comment]
@handrews this repository is deprecated. Current work is going on here: https://github.com/json-schema-org/json-schema-spec/

**Comment by handrews** [comment]
@erosb yes, I'm aware, and commenting more on issues at that repo.  I just thought the person who opened this issue might want to know that yes, there has been work on relative JSON pointer.

**Comment by handrews** [comment]
@mwherman2000 as this repo is deprecated, could you please close this?  There is no one remaining with the project who can close issues on this repo.

If you'd like to keep discussing this, please file it at [json-schema-org/json-schema-spec](https://github.com/json-schema-org/json-schema-spec)
