### ISSUE TITLE
Pattern Properties, AnyOf, and Ref

### ISSUE THREAD

**Issue by jdh6660** [json-schema/json-schema#241]
Why can't I do this? Is there a specific way to use anyOf?

`"patternProperties": {
    "^[A-Z]$": {
        "anyOf": [
	    {"&ref": "#/definitions/StringType"}, 
	    {"&ref": "#/definitions/NumberType"}
    ]
   }
 }`

**Comment by JanTvrdik** [comment]
Replace `&ref` with `$ref`
