### ISSUE TITLE
json-schema.org is not available

### ISSUE THREAD

**Issue by richseviora** [json-schema/json-schema#242]
The branch reference `gh-pages` seems to have disappeared.

**Comment by Julian** [comment]
There appears to have been some configuration missing here from @Acubed / @Relequestual? Not quite sure what step is missing, but I was trying to ping them -- I'll re-push a version of the branch to get the site back up, sec.

**Comment by Julian** [comment]
I've just re-pushed the branch, so should come back momentarily.

**Comment by Julian** [comment]
OK, it's back, sorry for the trouble here.

**Comment by Acubed** [comment]
Let's contact GitHub support, maybe they can help fix this. Multiple projects shouldn't be able to claim a single domain name >:(

**Comment by Relequestual** [comment]
oh =[ grrr. Hopefully they can shed some light on what happened!

**Comment by Relequestual** [comment]
I'm contacting github support
