### ISSUE TITLE
Is it possible to validate just the base objects?

### ISSUE THREAD

**Issue by jdh6660** [json-schema/json-schema#243]
Imagine we have Json with objects within objects, but the base objects are really our "Objects," the ones we define, the ones we want to validate.

Lets say we have a Json that looks like:

`"School": {
   "ClassRoom": {
      "Student1": {
           "Name": "Joe",
          "Age": 11
      },
     "Teacher": {
          "Name": "Mrs Adams",
         "Age": 29  
    },
   "SandBox": {
        "Student2": {
           "Name": "Kevin",
          "Age": 9
      },
      "Student3": {
           "Name": "Mike",
          "Age": 10
      }
   }
  }
}`

We dont know where the base objects are in the Json tree. But we want to validate that every person has a name and an age.

How do we construct a Json Schema to validate the base "Objects" ignoring the path to get there? I want to build a generic schema that validates my people Objects etc. I don't know how to use the patternProperties in this case because the pattern isn't always the same in my case.

**Comment by JanTvrdik** [comment]
For exampe

~~~json
{
	"definitions": {
		"person": {
			"type": "object",
			"properties": {
				"Name": {"type": "string"},
				"Age": {"type": "integer"}
			},
            "required": ["Name", "Age"]
		}
	},
	"type": "object",
	"additionalProperties": {
		"anyOf": [
			{"$ref": "#"},
			{"$ref": "#/definitions/person"}
		]
	}
}

~~~

**Comment by jdh6660** [comment]
What does `{"$ref": "#"}` do for us?

**Comment by handrews** [comment]
@jdh6660 :  `{"$ref": "#"}` refers to the entire schema.  So what this says is "every property should either validate as a person, or recursively apply this schema to each property's value."  This is what allows the person schema to "find" person instances everywhere.

If your instance is a tree of people, this is the schema you want.  If your instance may have other things in the object tree, it gets more complicated, but the same general idea applies.

If this answers your question, could you please close this issue?  There is no one remaining with this project who has permissions to close other people's issues on this repo.  If you want to discuss things further, could you still close this and instead open an issue at [json-schema-org/json-schema-spec](https://github.com/json-schema-org/json-schema-spec) or [json-schema-org/json-schema-org.github.io](https://github.com/json-schema-org/json-schema-org.github.io)?  Those are the currently active repos.

**Comment by jdh6660** [comment]
I figured it out something that worked eventually. Thanks.
