### ISSUE TITLE
Additional keyword for validating the content a link points to

### ISSUE THREAD

**Issue by seagreen** [json-schema/json-schema#244]
An example of how this would be userful: a user has a JSON document containing a link. They'd like to write a schema that makes that document invalid if the content that links points to doesn't itself conform to some other schema.

For example, in this situation:

`schema.json`:
```
{
  "properties": {
    "foo": {
      "linkContent": {
        "uniqueItems": true
      },
      "type": "string"
    }
  }
}
```

`data.json`: `{ "foo": "./more-data.json" }`

`more-data.json`: `[true, true]`

... validating `data.json` using `schema.json` would result in a unique items error.

EDIT: Fixed up the example since it was a mess before.

**Comment by seagreen** [comment]
My apologies if this has already been covered by JSON Hyper-Schema. I'm not a hyper schema expert, but I read through the spec and it seemed to be talking about using JSON Schema to make APIs, not about links within documents.

**Comment by seagreen** [comment]
Also since validation won't be deterministic perhaps this would be better suited as an optional validator? Though there is precedent since schemas using "$ref" aren't deterministic either.

**Comment by jdesrosiers** [comment]
I don't think you need a new keyword to achieve this.  You can do it with some creative use of `$ref`.  As you may or may not know, `$ref` is defined independently of JSON Schema as [JSON Reference](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03).  Therefore `$ref` is not just for schemas.  If you use `$ref` to represent your links, you can write your schema as if the data has already been resolved.  You just need one extra step before validation to resolve `$ref`s in the document.

For example (modified slightly from original for clarity):

**schema.json**
```json
{
  "type": "object",
  "properties": {
    "foo": { "type": "string" }                                                                                               
  }
}
```
**start.json**
```json
{
  "foo": { "$ref": "./more-data.json"}
}
```

**more-data.json**
```json
[true, true]
```

So, I wouldn't add a new keyword to support this functionality, but it would be nice if validator implementations supported dereferencing data as well as schemas.  It shouldn't be hard considering that it is no different than what is already being done for schemas.

**Comment by seagreen** [comment]
Gah :volcano: now I'm wondering if there's a single JSON Schema library that actually conforms to the spec!

(Assuming you're right that "$ref"s should be resolved before validation, but I have no reason to think otherwise)

I don't think this is anyone's fault, but that's the situation. If someone will make a list of all these edge cases I will do my best to get as many as possible into the JSON Schema test suite. I've only been doing this for some of the things I've come across so far, so I guess this is my fault as much as anyone's.

**Comment by seagreen** [comment]
In the meantime though, are we dead certain that "$ref"s should be resolved before validation? Is this undefined behaviour that's up to the validation library, or is it required?

**Comment by jdesrosiers** [comment]
I'm not sure what you mean.  I'm not suggesting that the way existing implementations work is wrong.  JSON Schema only expects `$ref`s to be resolved for schemas.  Resolving `$ref`s in the data being validated would either be a bonus feature or something a user does before passing the data to the validator.

**Comment by seagreen** [comment]
:+1: I see what you mean. I'm glad existing implementations are fine.

Unfortunately, while your "$ref" suggestion is definitely a good one to know about, I did realize it doesn't completely handle all the situations that could come up. For instance, what if you want to exclude the option of the data being included directly, and only allow it to pass validation if a link of some kind is used?

Like I said, this would be a departure from previous validators, so I understand if there's no interest in including it in the spec. It does seem like a situation that will keep coming up though.

**Comment by jdesrosiers** [comment]
Ok, you're right.  But, I'm failing to imagine a case where it would be necessary or useful.

**Comment by seagreen** [comment]
Well, we're both right:) You're still right that there _is_ a way to do validation across document lines, it just doesn't help in this case.

It's would be useful in cases where you have a set of JSON documents that link to each other, and you want to enforce that links in some situations can only go to some types of documents. For instance, Person documents can only link to another Person for a "father" key, etc. If you have a big chain of these links you might want to enforce that they are actual links instead of embedded documents -- particularly if, from the very beginning, you know there are going to be cycles (but there could also be lots of other reasons).

**Comment by seagreen** [comment]
I may try to put together a working implementation of this. If I do and it works I might bring this up again, in the meantime I'll close this issue unless anyone else is interested.
