### ISSUE TITLE
Relative json pointer does not allow to "get" object keys? (draft5)

### ISSUE THREAD

**Issue by alekbarszczewski** [json-schema/json-schema#245]
I am new to json schema draft 5 and just read about relative json pointer proposal.
However it seems that there is one case that is not covered by it.
Let's say I have following data structure:

```
{
  "categories": {
    "category1": { "title": "category 1 title" },
    "category2": { "title": "category 2 "title } 
  },
  "articles": [
    { "category": "category1", "content": "..." } // enum: { $data: "...?" }
  ]
}
```

It would be nice to restrict `articles[].category` value to keys in `categories` object.
I thought it could be done via `$data` and relative json pointer but it seems that it is not possible to reference object keys through relative json pointer. Is there any other option?

**Comment by HotelDon** [comment]
I'm not sure why relative json pointers don't allow you to reference object keys, it's a problem I ran into as well. The only solution I've been able to find is to collect all the object keys into an array programatically, and then having the $data reference point to that array. It's not exactly a very clean solution.

**Comment by handrews** [comment]
@alekbarszczewski :  Activity for this project has moved to https://github.com/json-schema-org/json-schema-spec
Could you please close this?  If you want to discuss this further, please re-file it there.
