### ISSUE TITLE
Allow anyOf/oneOf/allOf with one value instead of extends

### ISSUE THREAD

**Issue by christianbalzer** [json-schema/json-schema#246]
"extends" was removed in draft 4. Can you allow anyOf, oneOf, allOf with one value only to allow for the same functionality (inheritance)? That way, the JSON schemas would remain compliant with the latest draft of the spec...

http://json-schema.org/latest/json-schema-validation.html#anchor145

**Comment by erosb** [comment]
Hello,

this is repository is obsolete, issues should be created here:
https://github.com/json-schema-org/json-schema-spec

2016-06-14 11:24 GMT+02:00 christianbalzer <notifications@github.com>:

> "extends" was removed in draft 4. Can you allow anyOf, oneOf, allOf with
> one value only to allow for the same functionality (inheritance)? That way,
> the JSON schemas would remain compliant with the latest draft of the spec...
>
> http://json-schema.org/latest/json-schema-validation.html#anchor145
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/json-schema/json-schema/issues/246>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAQrBlXjtQUusbfhCqowxvWbt2hv-Pxkks5qLnNPgaJpZM4I1H1B>
> .
>



-- 


*Bence Erősme@github <https://github.com/erosb>*

**Comment by handrews** [comment]
@christianbalzer as @erosb notes this repository is obsolete.  Could you please close this issue?  There is no longer anyone involved with the project who has permissions to close other people's issue on this repo (which is why the repo is obsolete - no one who is still here can do anything with it).

**Comment by handrews** [comment]
@christianbalzer : BTW it is totally legal to use "allOf" with one value. The meta-schema explicitly gives it (and "anyOf" and "oneOf") a minimum length of one.

So this repo is obsolete and the thing you want should work- if it does not work in a particular validator it is a bug in that validator.  It would be really helpful if you could close out this issue.
