### ISSUE TITLE
Max value not being faked?

### ISSUE THREAD

**Issue by spaceribs** [json-schema/json-schema#248]
Faking the following schema:
```json
{
  "type": "integer",
  "minimum": 0,
  "maximum": 1
}
```
Generates `0` no matter what, shouldn't it be 50/50?

**Comment by awwright** [comment]
I'm confused, what is this in reference to?

This repository is only an old version of the specification, it doesn't generate any values.

**Comment by handrews** [comment]
@spaceribs if this is about the behavior of how a particular implementation handles that schema, could you please close this and file it against the implementation instead?

If it is a general question, could you please close this and open an issue at https://github.com/json-schema-org/json-schema-spec/issues with more details about how you think the standard should phrase the requirement?  As far as the standard is concerned, schemas don't "generate" any values, they are just applied to JSON that already exists.

Either way, please close this issue as this repo is abandoned and no one who remains here is able to close issues opened by other people.

**Comment by spaceribs** [comment]
Sorry, I had both tabs open at the time, apologies!
