### ISSUE TITLE
Domain name "json-schema.org" disappeared

### ISSUE THREAD

**Issue by radio-miskovice** [json-schema/json-schema#250]
Today (21 November 2016) I discovered that I cannot open website "json-schema.org" due to missing DNS records. I remember on Friday 18th it was still there, I am not sure about the weekend, though.

Is this a deliberate, planned transition, or just someone forgot to pay for the domain registration?

The problem is that some validation tools (e.g. jayschema) that can chain schemas during validation, rely on referred schemas being reachable on the URL specified in id attribute.   Obviously, http://json-schema.org/schema, being the ultimate root of all other schemas, will break such validation if not present.

Is there anything I can do to fix this?

**Comment by Relequestual** [comment]
@radio-miskovice Please close in favour of https://github.com/json-schema-org/json-schema-org.github.io/issues/48 - Thanks.

**Comment by radio-miskovice** [comment]
Thanks. Done.
