### ISSUE TITLE
how would I build a json schema that is not allowing empty elements {} at all, ever?

### ISSUE THREAD

**Issue by iamveritas** [json-schema/json-schema#251]
how would I build a json schema that is not allowing empty elements {} at all, ever?
obviously I have no experience with json schemas... and searching for this on docs online didn't helped me.
thank you

**Comment by sgpinkus** [comment]
Should ask at SO or something not here, but, think you want something like:

> {
  "type": "object",
  "minProperties":  1
}

**Comment by iamveritas** [comment]
thanks
what is SO

**Comment by epoberezkin** [comment]
StackOverflow: https://stackoverflow.com/questions/ask?tags=jsonschema

**Comment by handrews** [comment]
@Julian if you get a chance could you close this?
