### ISSUE TITLE
json-schema transformation and normalization specification

### ISSUE THREAD

**Issue by nickl-** [json-schema/json-schema#43]
While considering the plausibility of  and use cases where one might require different value types for a single type definition https://github.com/json-schema/json-schema/issues/38#issuecomment-11461515 an alternative approach came to mind, data normalization through transformation.

given the following json data example

``` json
{
    "animation": "on",
    "rotate": "off",
    "show-splash": true,
    "hide-desktop": false,
    "repeat": 1,
    "delay": 0,
    "screensaver": "enabled",
    "password-protect": "disabled"
}
```

While validating (more specifically while transforming but since validation can only occur once transformation is complete there is a dependency) fields defined with simple transform strings
can process the data and produce an altered form.

``` json
{
    "type": "boolean",
    "transform": ["/on|enabled|1|true/true/", "/off|disabled|0|false/false/"]
}
```

Resulting normalized form after validation.

``` json
{
    "animation": true,
    "rotate": false,
    "show-splash": true,
    "hide-desktop": false,
    "repeat": true,
    "delay": false,
    "screensaver": true,
    "password-protect": false
}
```

As a separate spec which can be presented to IETF as additions to the json-schema specification we should consider:
- the different use cases where this might be useful/applicable
- research and compare notes with any current practices of transformation (XSLT comes to mind)
- consider the different approaches by which to facilitate the requirements
- reach a consensus on the target requirements and optimum implementation
- draft RFC document
- write reference implementation for transformation
- submit completed specification.
- etc.

**Comment by alexweissman** [comment]
I know this is an old (and it seems contentious) thread, but has there been any renewed effort to develop a JSON Transform standard?  

I am very interested in using JSON Schema along with some standard for specifying data transformations in my projects ([UserFrosting](http://www.userfrosting.com/) and [Bootsole](https://alexweissman.github.io/bootsole/))

Standards projects like this are extremely important, I wish there were more!
