### ISSUE TITLE
Can't find a way to restrict that some pattern-matched property is required (v4 and lower)

### ISSUE THREAD

**Issue by P-Product** [json-schema/json-schema#47]
I would like to find a way to specify that an instance MUST have a property that matches a regex. Or, more generally, specify a list of regular expressions that ALL have to be matched by some properties in the instance.

**Comment by handrews** [comment]
@P-Product this repo is now deprecated and I've re-filed this topic at json-schema-org/json-schema-spec#106

If you could close this issue, that would be much appreciated.
