### ISSUE TITLE
patternRequired: how should it be defined?

### ISSUE THREAD

**Issue by fge** [json-schema/json-schema#59]
This is the last keyword which will be added to draft v4 (it was proposed by @P-Product in issue #47).

However, what the value of this keyword should be is not defined yet.

I see two possibilities:
- An array; it must have at least one element; each element must be a string, and each string must be a valid pattern; all elements must be unique. Example:

``` json
{
    "patternRequired": [ "^p", "\d+$" ]
}
```

An (object) instance is valid against that keyword if and only if each regular expression matches at least one property name in that object.
- An object. Each member name of that object must be a valid regular expression. Each value must be an integer, and each integer must be greater than 0. Example:

``` json
{
    "patternRequired": {
        "^p": 2,
        "\d+$": 1
    }
}
```

An (object) instance is valid against that keyword if and only if for each (regex, number) specified, at least this number of properties exists in the object instance which are matched by the regex.

I'd rather go with the array definition myself. One could also add that the unique element constraint is kind of useless, since `"^"` and `"$"`, for instance, are unique but match the same things exactly. But it "does not hurt" anyway.

Thoughts?

**Comment by handrews** [comment]
@P-Product this repo is now deprecated.  I've filed the min/maxPatternProperties issue at
json-schema-org/json-schema-spec#106 if you'd like to continue the discussion.

This issue should be closed.
