### ISSUE TITLE
Website: clearly mark implementations by supported version

### ISSUE THREAD

**Issue by geraintluff** [json-schema/json-schema#72]
Now that there are new drafts with the IETF, I think we should group the software/implementations by the supported version.

It might also be worth raising issues on the projects for the various tools, requesting support for the latest draft, and noting that they are about to be categorised as "not supporting the latest version" on the JSON Schema main site.  Thoughts?

**Comment by handrews** [comment]
If anyone comes along and would like to pick this up, the appropriate new repo is at:
https://github.com/json-schema-org/json-schema-org.github.io

This repo is deprecated.
