### ISSUE TITLE
Prove the usefulness of JSON Schema on the web site: write schemas for existing JSON based protocols

### ISSUE THREAD

**Issue by fge** [json-schema/json-schema#74]
I have already started. I have written schemas for:
- GeoJSON,
- JSON Patch.

I'd say it would be great if the site included such examples. Along with examples to schemas already written by third parties.

Comments?

**Comment by nfroidure** [comment]
@fge, how did you manage to validate GeoJSON lat,lngs ? http://geojson.org/geojson-spec.html#appendix-a-geometry-examples

Since it is an array, i can't manage to validate the lat,lng order with JSON Schema. Best i could do is this:
```js
{
  latLng: {
      type: 'array',
      minItems: 2,
      maxItems: 2,
      items: [{
        anyOf: [{
          type: 'number',
          minimum: 0,
          maximum: 90,
        }, {
          type: 'number',
          minimum: -180,
          maximum: +180,
        }],
      }],
    }
}
```

Am i missing something ?

**Comment by nfroidure** [comment]
Found this https://github.com/fge/sample-json-schemas/blob/master/geojson/geometry.json#L63. I think i've got a PR to do ;)

**Comment by handrews** [comment]
If anyone would like to pick this up in the form of a PR or re-filed issues, please do so at the new repo:
https://github.com/json-schema-org/json-schema-org.github.io

This repository is deprecated
