### ISSUE TITLE
Proposal for next draft: Remove 'id' keyword

### ISSUE THREAD

**Issue by gazpachoking** [json-schema/json-schema#77]
So, I propose "id" keyword is removed from the next draft of json schema. Caveat: I have not implemented many schemas, so maybe I am missing some areas where it is extremely beneficial.

My objections:
Inline dereferencing:
- inline dererferencing is optional. It does not do anyone favors to have schemas that are not portable between implementations
- it is not trivial to scan a json schema and identify which "id" keys are actually keywords, for example:

``` json
{
    "x": {
        "id": "it is impossible to know if this is an id keyword or not"
    }
}
```

``` json
{
    "dependencies": {
        "id": "this is not an id keyword"
    }
}
```

Canonical dereferencing:
- due to the `id` keyword, it is possible to have `$ref`s that are in a different scope, depending on how they are referenced. consider:

``` json
{
    "id": "base",
    "items": {
        "id": "anitem",
        "anyOf": [{"$ref": "#/x"}]
    },
    "properties": {
        "a": {"$ref": "#/items/anyOf/0"}
    },
    "x": {"type": "integer"}
}
```

  the `$ref` within items has a different scope depending on if we are evaluating it from the `items` keyword (anitem#/x) or the `properties` keyword (base#/x). JSON reference does not have this problem, as the scope is always the uri of the document.

Maybe I just need to see some examples where `id` is highly beneficial, but it seems to me that you might want to use the `id` property, you could just as easily `$ref` the external schema. Simple inline referencing to fragment ids might be helpful in some situations, but scanning an arbitrary json object to identify them is not. And given the `definitions` keyword, it is much more helpful to use json pointer references to subschemas stored within that keyword. I just do not see the the benefit of `id` outweighing the difficulty if implementing it, especially given support may not be consistent throughout implementations.

**Comment by seagreen** [comment]
I wonder how many JSON schema implementations currently implement "id" correctly? Until this gets finished: https://github.com/json-schema/JSON-Schema-Test-Suite/issues/20 (if ever) we may have to compile the list by hand, but it still wouldn't take too long.

**Comment by sam-at-github** [comment]
@Acubed tl;dr - most of it. Fact is, there is a clear problem with id, but I think in general people get caught up in false dichotomies. 

:-1: for removing the id keyword
:+1: for renaming the id keyword, "$id", to avoid conflicts @gazpachoking mentioned in first post.
:+1: for deprecating using the id keyword for base URI resolution. This is hideous.
:+1: 2 types of references JSON Pointers (#/foo) and flat refs ("#foo") that ref an id (or rather an "$id").
:+1: For there not being one non optional simplified type of dereferencing not "canonical" and "inline". 

@fge analyses this well in https://github.com/json-schema/json-schema/wiki/The-%22id%22-conundrum#how-to-fix-that. Completely agree with that.

As an aside, I would say its worth looking at how [XSD](http://www.w3.org/TR/xmlschema-0/) does internal and external refs (much more restrictive than is proposed in json schema v4), and how [HTML does base URI adjustment](http://www.w3.org/TR/html401/struct/links.html#h-12.4) (with a different keyword -- and who *actually* uses `base` in HTML anyway...)

**Comment by handrews** [comment]
@gazpachoking a number of things about id and $ref have been tidied up in the latest internet draft.  Spec work for that is going on at https://github.com/json-schema-org/json-schema-spec
Could you please closes this, and if you still have concerns with the new wording, open issues for those at the new repo?

https://tools.ietf.org/html/draft-wright-json-schema-00
https://tools.ietf.org/html/draft-wright-json-schema-validation-00
https://tools.ietf.org/html/draft-wright-json-schema-hyperschema-00
