### ISSUE TITLE
Website theme, implementations and test suite integration

### ISSUE THREAD

**Issue by nickl-** [json-schema/json-schema#79]
@json-schema 
## JSON Schema Test Suite

A lot of hard work has gone into the [Test Suite](/json-schema/JSON-Schema-Test-Suite) (Well done guys and thank you to all our contributors, you rock!) and we also had requests to add JaySchema #76 and JeSSE #78 to the lists of implementations. 

It is time to take things to the next level.
## Strategy

When the Test Suite [was invited](https://github.com/json-schema/JSON-Schema-Test-Suite/issues/11) to join us at json-schema  the strategy was two-fold.
1. to combine efforts and increase community buy in.
   This has already proven beneficial especially with the D4 updates.
2. to be incorporated into the implementations list on json-schema.org as our official compliance authority.
   Which is what this post and subsequent tasks will aim to address.
## Implementations

Before it was removed the implementations were collected into a sortable list which got automatically updated with realtime information from the projects and included download links to the latest releases (based on release tags) and links to the project sites, the # of Open issues, # of Watchers and # of Forks are used to indicate community involvement, and when last updated to indicate health. The category, license, schema version etc is also included in the table and can be sorted to your liking when looking for a suitable project to meet your requirements.

The live information is currently from GitHub's API only (as indicated by the octocat logo) the idea was to incorporate other favourite project hosting environments before the set back which we still need to address.

What the table looked like.
![implementations](http://img.viame-cdn.com/photos/6ccf75e0-60c6-0130-5f1a-1231391615b5/r600x600.jpg)
Latest rankings in comparison to another [screenshot taken a moth ago](/json-schema/JSON-Schema-Test-Suite/issues/20)

The idea is to somehow incorporate actual Test Suite results to the table but there are a number of obstacles to overcome first to get back to where we were. This caused progress on devising a strategy for how to accomplish this to lack behind. Once we have the functionality ported back and regained a platform for its inclusion we will continue planning and ultimately resolve the 2nd item of our strategy. Lots of work still to be done.
## Obstacles

The work done on the implementations table is still available but the current style applied to the site is posing a problem. It would already be a task to incorporate the implementation and keep the content changes currently done without still having to adapt to a custom style.

My feeling is that it would be easier to get the current site back on bootstrap (which is well known so skills are readily available) than to try and make the table work on the custom style. I also prefer blue to green but that is a matter of personal taste and should not affect our decisions here.
## Project status

While we subject the implementations to scrutiny the same goes for our project and it is useful for users to be able to see at a glance, who is involved, what the stats are and the last activity on the project.

This is what we had before which can also return:

![project status](http://img.viame-cdn.com/photos/36aedcc0-60c9-0130-6d8a-22000a1e9a8e/r600x600.jpg)

The information, like the implementations table is pulled from github in real-time and requires no maintenance. The github ribbon, which links back to the github project, is also a common occurrence for community sites and I would consider our public presence  incomplete without it. 

Once we've done the effort to get things back there is lots more that can be added for example real-time analytic stats et. al.
### Semantics:
- The links must all have id attributes for analytics, this was raised before (reference to which is lost because of the new and improved strategy as we've lost the off site repos)
- Heading tags should have ids to facilitate direct linking.
- Meta data the most appropriate schema.org entity for implementations seem to be [SoftwareApplication](http://schema.org/SoftwareApplication) The closest thing that relates to open source projects it would seem is the general [Organization](http://schema.org/Organization) entity, any suggestions?
### Encourage involvement

There is a lot that can be done to encourage people to contribute.
- Expressed need for contributions
- How to contribute
- Where we need help
- etc

People are eager to help and I because we are a little different to your usual OSS projects we need to make extra effort to educate others on what we do, where we are going, how they can help. This is currently not adequately addressed on our website. 

Apparently wording like "You alone have the power to consciously choose unity and see it materialize or choose to decline and we stand divided and all shall be in vain." if I understood the objections correctly but instead of focusing on what we don't want lets rather come up with proactive suggestions that can be implemented or see something similar return. Suggestions and strategies are welcomed here...
## Conclusion

This is a proposed strategy that will be put into action unless motivated objections -1 are made. If you have any suggestions or additional requirements you would see met you are welcome to raise those topics too. Approval is assumed and does not require a comment, give +1 to indicate an availability and willingness to help with the efforts.

Even though the great purge has caused unnecessary rework to be done there is nothing we can do about it now. Lets let bygones be bygones and move along no hard feelings! This is not a platform to re-debate the past and the focus is to realign ourselves with the strategy and accomplish our goals. 

If you have nothing to add to the topic, by which to aid us in accomplishing the huge task ahead. If you find anything in here that strongly offends you or consider a personal attack I suggest you revaluate your commitment to the community and motivations for joining us in the first place. If what you have to say is not constructive and aiding this task I ask that you keep it to yourself or raise it in a separate issue. **No attempts to derail this thread and spread discourse will be entertained.**

That's it from me, lets hear what you have to say...
Lets make something truly awesome! =)

**Comment by handrews** [comment]
@nickl- 
This project is active again, with a new internet-draft published, so if you'd like to pick this back up please check out the new repos (including the test suite repo) at
https://github.com/json-schema-org
