### ISSUE TITLE
Sections on protocols redundant or unnecessary

### ISSUE THREAD

**Issue by awwright** [json-schema/json-schema#80]
Sections "5.3.  JSON Schema and HTTP" and "5.4.  JSON Schema and other protocols" should not be necessary. The semantics of JSON Schema does _not_ change because the document is being sent over HTTP. The specification merely defines how JSON Schema may be used within the context of HTTP, including the Link header, and this does not affect how the JSON Schema is actually processed (and therefore, does not change its semantics).

As such these sections should be removed entirely.

**Comment by handrews** [comment]
@awwright I think you fixed this :-)  Would you be willing to close this issue out?  Thanks.
