### ISSUE TITLE
URI vocabulary: "URI" vs. "URI reference"

### ISSUE THREAD

**Issue by awwright** [json-schema/json-schema#81]
"7.2.1.  Valid values" specifies:

> The value for this keyword MUST be a string, and MUST be a valid URI. This URI MUST be normalized, and SHOULD NOT be an empty fragment (#) or the empty URI.

This is contradictory, either the property value must be an absolute URI (in which case "#" would not be a valid URI), or it must be a URI reference (in which case saying the URI MUST be normalized does not make sense).

The intent of the URI is clearly to allow a URI reference here:

> URI references in information retrieval systems are designed to be late-binding: the result of an access is generally determined when it is accessed and may vary over time or due to other aspects of the interaction.  These references are created in order to be used in the future: what is being identified is not some specific result that was obtained in the past, but rather some characteristic that is expected to be true for future results.  In such cases, the resource referred to by the URI is actually a sameness of characteristics as observed over time, perhaps elucidated by additional comments or assertions made by the resource provider.

Additionally, all media types I know of allow a URI reference when defining a new base URI. (Including HTTP, XML, Turtle, HTML, JSON-LD, etc.)

Instead of explicitly prohibiting <#> as a value, it should be noted that <> and <#> defines the same resource, (and link to JSON Reference in doing so), and therefore <#> would not be a valid value (if re-defining existing schemas is to be an error condition).

In section "6.1.  Purpose":

> The value of this keyword MUST be a URI [RFC3986] and a valid JSON Reference [json‑reference]; this URI MUST be both absolute and normalized. The resource located at this URI MUST successfully describe itself. It is RECOMMENDED that schema authors include this keyword in their schemas.

Much of this is redundant, a URI must already be absolute, though not necessarily normalized. I don't see a problem with this redundancy, though.

JSON Schema Validation section "7.3.6.  uri" does not specify if the "uri" format is a URI or a URI reference. While almost all fields for a URI will probably want to be a URI reference, only being able to specify an absolute URI does not make much sense. There should probably be two formats, "uri" and "uriref" or similar (we should shop around other media types and see what names they use to make the distinction, RFC 3986 uses "URI" and "URI-reference" respectively).

... And lots more sections.

**Comment by handrews** [comment]
@awwright I think you fixed this :-)  Would you be willing to close this issue out?  Thanks.

**Comment by awwright** [comment]
@handrews You're killing me with all these issues you're resurrecting
