### ISSUE TITLE
URI vocabulary: "resolution scope" -> "base URI"

### ISSUE THREAD

**Issue by awwright** [json-schema/json-schema#82]
To be compliant with RFC 3986, JSON Schema must not define its own URI resolution behavior, but instead should refer to the standard for this behavior. This standard refers to a "base URI" and as such, JSON Schema should define what establishes a base URI, instead of inventing a new vocabulary term and (mostly redundantly) re-defining its behavior.

Also note that external mechanisms may introduce their own base URI, RFC 3986 specifies a "Base URI of the encapsulating entity (message, representation, or none)", a "URI used to retrieve the entity", and a "Default Base URI (application-dependent)". All of these are implementation specific, and defined by the protocol or respective media types, not JSON Schema.

**Comment by handrews** [comment]
@awwright I think you fixed this :-)  Would you be willing to close this issue out?  Thanks.
