### ISSUE TITLE
New "informative" keywords

### ISSUE THREAD

**Issue by geraintluff** [json-schema/json-schema#87]
I think there might be a growing category of keywords which are not simply display-related, not validatable, and not hypermedia-related.

They describe either some non-validatable nature of the format, or they provide "processing hints" for certain situations.

The two examples I'm thinking of in particular are `"propertyOrder"`, and `"unordered"` - however, I think that the existing keyword `"format"` might be in this category as well.
- `"propertyOrder"` does not describe the JSON data - however , it is useful when processing JSON objects in situations where unordered maps are not available.  This includes: translation to non-JSON formats, or creating database tables for schema-based ORM libraries.
- Similarly, `"unordered"` would apply to arrays, and is useful statement about the format, even though it is not validatable.
- I also think that `"format"` could fall under this category.  Validators are allowed to completely ignore it - however, it tells you useful information about the format.  If an number has a format "utc-millisec" (defined in v3) then that places _no validation constraints at all_ - it is simply "informative" about the nature of the data or the intended processing.

I think that these keywords should be grouped together (including `"format"`) and included in the spec.

**Comment by ewildgoose** [comment]
I think that a structured way to add additional metadata to JSON-schema is vital.  In addition to the cases above, I would desire to use json-schema to describe arbitrary APIs found in the *real world*.  And it would additionally be useful to tag properties with information that is helpful when converting format, ie to something other than JSON.  

Some examples of real world oddities (ie I didn't write them, I just need to interface to them)

- value is an int 0-250, but there are also some "special values" , eg 251 means something like "very large +ve", 252 means "infinite", 253 means "unknown", etc.  Or 0 is "null".

- value is scaled in some arbitrary way, eg lat/lon is supplied as an int "DDmmm", so you need to divide by 1000 to get back to DD.mmm. Or distance supplied in furlongs/chains, etc (sigh...). Combine this will special cases above, eg value is distance, but anything larger than 1024 means "lots and lots/infinite/unknown"

- noting the units some value is supplied in, eg degrees centigrade of Fahrenheit. 

- binary encoding formats, eg it might be an int between 1-27, but it's stored as 32 bits when encoded 

- API only accepts properties in a certain order, or there is some serialisation into a binary where order is important.

I would propose that the standard would benefit from a "metadata" property which is a free for all to bundle in metadata metadata unrelated to the core job of validating a property.  Additionally there is some value in trying to offer guidance for default names for more common possibilities, eg "order", "units", "scaleFactor".

Arguably the existing metadata (description, title, default) could be moved into this property?

Thanks for your consideration

**Comment by jdesrosiers** [comment]
A `metadata` property is not necessary.  JSON Schema ignores any keyword it doesn't know.  Therefore, any undefined keyword you include in a schema is effectively a meta-data keyword.

**Comment by Anifacted** [comment]
@jdesrosiers you could argue that a `metadata` property could be useful in that it keeps your custom properties in a safe namespace, thus preventing possible future collision with new identical keywords introduced in the spec.

I know that versioning will make sure that this doesn't happen before you actively bump the version number of your schema, but even so, it would be nice to know that you could safely do that without worrying about your own properties, no?

**Comment by jdesrosiers** [comment]
@Anifacted, if I felt like a meta-data property I introduced needed to be namespaced, I would include that namespace in the name of the property.  For example, if I wanted to add property `foo`, I might name it something like `myProject.foo`.  I think this form of namespacing makes for easier to read schemas.

However, that is all a moot point.  If you choose to use a `metadata` keyword to group your custom properties, you can do that without adding a keyword to the spec.  The `metadata` keyword would just be another property that gets ignored.  It is unnecessary to add it to the spec.  In fact, I would consider it bloat.

**Comment by Anifacted** [comment]
@jdesrosiers That's a really fair point. I guess the only reason for including it in the spec would be to secure the `metadata` property itself from possibly meaning something else in a future version, though I agree that this is a bit of a shallow argument, since it's unlikely that that would ever happen.

**Comment by handrews** [comment]
@kennardconsulting @Anifacted @ewildgoose @Fannon @martinpengellyphillips 
As the others in this issue know, work has moved to https://github.com/json-schema-org/json-schema-spec

If anyone wants to champion any of these proposals, please re-file them (perhaps one issue per proposal?) at the new repo.
