### ISSUE TITLE
Example schemas extracted from schema.org?

### ISSUE THREAD

**Issue by geraintluff** [json-schema/json-schema#96]
I've written a Python script ([Gist here](https://gist.github.com/geraintluff/5951030)) that takes a machine-readable version of the schema.org definitions (from http://schema.rdfs.org/all.json) and outputs a JSON Schema for each type.

They're not perfect, and some of them could do with hand-tweaking (for example I would like to give the "Thing" type some specialised improvements), however I think it might be a good source of example schemas.  Most of them wouldn't need any modification, I think.

There's even the possbility that once we've polished them enough, we could try and get them either mentioned by or hosted on the main schema.org site, which would be pretty good publicity for us.

**Comment by handrews** [comment]
Active work on the website and examples is now at https://github.com/json-schema-org/json-schema-org.github.io
