### ISSUE TITLE
pattern / patternProperties example is wrong

### ISSUE THREAD

**Issue by Julian** [json-schema/json-schema#97]
http://json-schema.org/latest/json-schema-validation.html#anchor69 seems to be an example for the section immediately preceding it, which is for `additionalProperties : false`, but that's not in the schema in the example.

Without it, AFAIU, that instance is valid, despite additional properties that don't match properties and patternProperties.

**Comment by handrews** [comment]
@Julian this was all rewritten in the latest internet-draft.  Could you please close this out?

Further concerns may be filed at https://github.com/json-schema-org/json-schema-spec

https://tools.ietf.org/html/draft-wright-json-schema-00
https://tools.ietf.org/html/draft-wright-json-schema-validation-00
https://tools.ietf.org/html/draft-wright-json-schema-hyperschema-00

**Comment by Julian** [comment]
Done.
