### ISSUE TITLE
Keyword names bad in address example, uses dashes instead of camel case

### ISSUE THREAD

**Issue by ottok** [json-schema/json-schema#98]
In http://json-schema.org/address the keywords are like `post-office-box`, `extended-address`, `street-address` etc. In all other examples the keywords are named in camel case and not using dashes (e.g. `familyName`, `givenName` etc).

(Although to be exact, the JSON Schema core does not define how keywords should look, so using dashes or underscore is technically not wrong, just not in style.)

**Comment by handrews** [comment]
@ottok this repo is now deprecated, and it would be much appreciated if you could close out this issue.  We no longer have permissions to do so.
If you'd like to take a look at this in the new repo, it is at
https://github.com/json-schema-org/json-schema-org.github.io

**Comment by ottok** [comment]
I am not using json-schema actively, so I'll just close this issue as unresolved and will not check or re-file it in the new repo.
